### ISSUE TITLE
Index proposal thresholdConst

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#100]
The Proposal entity indexs some but not all of the parameters defined ehre: https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L28

We at the moment also neet `thresholdConst`. May need more in the future.

**Comment by ben-kaufman** [comment]
https://github.com/daostack/subgraph/blob/master/src/domain/proposal.ts#L116
The parameters are already cached...

@jellegerbrandy does that solves this issue?

**Comment by orenyodfat** [comment]
thresholdConst is indexed .
