### ISSUE TITLE
index "confidenceThreshold" on the proposal entity

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#108]
This refers to the confidenceThreshold at the time when the proposal entered the preboosted state

**Comment by orenyodfat** [comment]
we can add that ,though if the proposal has tokenNeedToBoost and downStakeToShiftBackToQ ...is that really needed ?

**Comment by jellegerbrandy** [comment]
As the specifictaions are now https://docs.google.com/document/d/1cYSX9Z6RmjSlJLPVKm6fwi4nnk2xrB0-NqXngVv61TY,  the "downStaketoShiftBackToQueue" is probably good enough. 


Can we find better names, though? Perhaps we can use `upstakeNeededtoBoost` (instead of tokensNeededToBoost) and `downStakeNeededToQueue` so they are more similar?

**Comment by orenyodfat** [comment]
@jellegerbrandy seems like this issue is duplicate on other issues.
please close it if it is not needed .
current name is 'confidence' on the proposal entity.
