### ISSUE TITLE
All proposals think they have 100000000000 stakesAgainst, when they dont

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#117]

**Comment by ben-kaufman** [comment]
I think that's just the automatic stake the DAO put on each proposal

**Comment by tibetsprague** [comment]
ah right, it's so small though it appears as nothing in the UI right now, we should think about how to show that.

**Comment by orenyodfat** [comment]
this issue might be relevant to https://github.com/daostack/migration
