### ISSUE TITLE
Calling execute on a Queued proposal that has expired breaks the subgraph

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#128]
It seemingly no longer updates it's index at at all after this

**Comment by orenyodfat** [comment]
which state of the proposal it does not update ?

**Comment by orenyodfat** [comment]
@tibetsprague

**Comment by jellegerbrandy** [comment]
As far as I understood from the conversations on discord, it stops indexing completely.

**Comment by orenyodfat** [comment]
cannot reproduce that .
I guess we need a test for that.

**Comment by ben-kaufman** [comment]
I'll try to replicate that...

**Comment by tibetsprague** [comment]
@orenyodfat it doesn't update from Queued to ExpiredInQueue, and then the whole subgraph breaks
