### ISSUE TITLE
Add  accountsThatCanClaimRewards property on the proposal entity

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#146]
This is born from the requiriement from alchemy that we want to show a list of proposals that still have rewards to be claimed, filtered by user (and other proposal properties)

The idea is that `accountsThatCanClaimRewards`contains all addresses of beneficiaries of `gpRewards` that have unredeemed rewards

**Comment by ben-kaufman** [comment]
Solved by #148
