### ISSUE TITLE
gpRewards contains records that have no claimable rewards at all

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#147]
If I run this query ```{ gprewards {
    id
  
  	tokensForStaker
  reputationForVoter
  reputationForProposer
  daoBountyForStaker
  
    
  }
} ```

I see records such as:

```
      {
        "daoBountyForStaker": null,
        "id": "0xd338579ef3105083c155df9a92e27bf77d754dd8c58d455bad9ed3f00f043b2c",
        "reputationForProposer": null,
        "reputationForVoter": null,
        "tokensForStaker": null
      }
  
```
These are not useful in any way, as far as I can see. Am I missing a point, or is this a bug?

**Comment by ben-kaufman** [comment]
@orenyodfat do you know why that happens?

**Comment by ben-kaufman** [comment]
@jellegerbrandy I think that the empty ones are rewards before the proposal is executed.
I'm not sure if we need that, do we?

**Comment by ben-kaufman** [comment]
I think I spotted a different bug though, it seems like the gpRewards doesn't work for `reputationForVoter`.

**Comment by jellegerbrandy** [comment]
Ok, that might explain it...

**Comment by ben-kaufman** [comment]
@jellegerbrandy can we close this issue then?
