### ISSUE TITLE
The dao collection should only return indexed DAOs

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#152]
At the moment, the daos colection contains all registered daos, but they are not all being indexed by the subgraph.

We need a way to distinguish them, so we can show only the working DAO instances in alchemy. 

This can be solved in one of two ways:

- only return DAO entitities that are indexed
- add a `isIndexed` property to  the DAO entity

I personally prefer the first.

Related front-end issue: https://github.com/daostack/alchemy/issues/437#event-2208603649

**Comment by orenyodfat** [comment]
Once we will have the ability to dynamically adding addresses to subgraph..it will all be indexed.
I guess that alchemy knows which DAOs are indexed ...(maybe via the migration.json) in order to do web3 txs..no?

**Comment by jellegerbrandy** [comment]
I think this is a subgraph _bug_: it is showing FALSE info (i.e. you can query for proposals of a DAO, but you will get 0 results even if the DAO has proposals). 

Regarding your proposed workaround:  yes alchemy does have access to the migration repo, and we can hack around this problem in the way you describe. But it is a very bad pattern to not have a single source of truth. 
I much prefer that the information we show in alchemy comes from the subgraph only, and not from a configuration file like `migration.json`.

I'm not sure why you think it would be better to resolve this alchemy-side.

**Comment by orenyodfat** [comment]
Well, my question was taken too far.
How does alchemy currently getting the list of addresses it interact with? 
  
If it is a bug (as you describe) we will take a look.

Again: 
- Once we will have the ability to dynamically adding addresses to subgraph..it will all be indexed.

**Comment by jellegerbrandy** [comment]
"Once we will have the ability to dynamically adding addresses to subgraph..it will all be indexed."

yes I get that. And you are telling me: "until that time, just hack around it in alchemy, and the undo that hack once we have dyanmically added addresses". And I'm saying: "better do the temporary hack in the subgraph: because now the subgraph is returning false info"

(Alchemy is getting the DAO addresses from the subgraph, but is getting (some) other contract addresses from the migration.json. I'm unhappy about that, we've discussed this some months ago - I argued that the subgraph should somehow make available all contract addresses it is indexing, so we do not have to rely on migration.json to get them.)

**Comment by ben-kaufman** [comment]
According to The Graph team, we can't access the list of addresses of indexed contracts directly from the subgraph. But what I would propose is to query the graph node part which stores it and use the addresses from there to filter the DAOs. You can get the list of addresses by:

1. Go to this path of the subgraph `http://localhost:8000/subgraphs/graphql` (replace localhost:8000 with whatever url and port you use.

2. Query this:
```
{
  ethereumContractSources {
    address
  }
}
```

**Comment by jellegerbrandy** [comment]
That is a nice hack, but not very useful as adding a new graphql endpoint is a considerable change, and I have those addresses anyway in migration.json. 

But you guys are missing my point.  

it is not difficult to get the contract addresses from the migration.json file in alchemy, and just return those.  It is ugly, but I can do it.

My point though is that the current graphql queries are returning wrong resultt. If you look at this query: https://rinkeby.subgraph.daostack.io/subgraphs/name/daostack-alchemy-rinkeby/graphql?query=%7B%20daos%20%7B%0A%20%20id%0A%20%20proposals%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D%7D

you will see some DAOs with no proposals. But in actually, we do not know if those DAOs have proposals or not; they are simply ot being indexed. This is wrong. And the fact that the subgraph returns thewrong data is not something we should "fix" in the frontend client, we should fix it where it is broken.

**Comment by ben-kaufman** [comment]
Ok, but the only way to fix that is to add the addresses somewhere hardcoded in the subgraph which is a bit ugly to do...

**Comment by jellegerbrandy** [comment]
But don't you have the addresses  already hardcoded in the subgraph?

**Comment by ben-kaufman** [comment]
No, at least not in an accessible part...

**Comment by ben-kaufman** [comment]
@jellegerbrandy so do you want me to add this filtering anyway?

**Comment by orenyodfat** [comment]
See arc-hive

**Comment by jellegerbrandy** [comment]
what is "arc-hive"?

**Comment by jellegerbrandy** [comment]
Ok, so we are doing the filtering client side after all (sorry about that Ben) while waiting for the arc-hive ...
