### ISSUE TITLE
DAO stats on the DAO entity

### ISSUE THREAD

**Issue by A-Zak** [daostack/subgraph#168]
Hi, we'd like to show some stats about each dao on the DAO selector page ([this is the design](https://zpl.io/a3e0nK1))...

Ideally, we would like to have a way to query these fields:
• Monthly active users (active = sent a tx)
• Monthly new proposals 
• Monthly GEN staked
Where monthly = in the last 30 days

If those are too complex to implement atm, we could in the meantime show these:
• Reputation holders - just a count, not related to activity
• Open proposals - just a count
• GEN staked - on all open proposals

**Comment by A-Zak** [comment]
@orenyodfat @ben-kaufman

**Comment by orenyodfat** [comment]
subgraph already index all the data which are needed to calculate the above.
This work can and should be done on the client side (subgraph user)

**Comment by tibetsprague** [comment]
@orenyodfat i disagree, its much more expensive to pull the list of all the open proposals for each DAO and calculate the GEN stakes on each one on the client every time we load the DAO list then in the subgraph.

**Comment by orenyodfat** [comment]
so you want the dao entity will maintain the following fields : 
- numberOfReputationHolders
- numberOfOpenProposals
- totalStakeOnOpenProposals

**Comment by A-Zak** [comment]
What I really want is to have the first list, but as I said, if this is much easier, then - yes, please :)

**Comment by jellegerbrandy** [comment]
The first list with the running totals is something that needs to be though through a bit before implementing, and it would be better to spec that as a part fo a more generic "what kind of statistics do we want from the subgraph" question (instead of this ad hoc issue)

**Comment by ben-kaufman** [comment]
I agree with @jellegerbrandy 
Anyway, I'm not sure the first list can be implemented in graphql. As for the second. I think we already have `membersCount`. We can also add proposals count and GEN staked but I think we should wait as Jelle said.

**Comment by A-Zak** [comment]
I think @jellegerbrandy  suggested we wait with the other the (more complex) first list - which I'm ok with. 
We would love to have at least some stats to display now /:

**Comment by tibetsprague** [comment]
maybe there's an easy query we can do now to get all the stakes on currently open proposals? i havent figured it out yet

**Comment by orenyodfat** [comment]
@A-Zak please prepare a specification for the DAO stat that you need .
Please get into details and address questions like :
- Does activeTotalStakes include or exclude the DAO downstake ?
- Do we need upStake and downStake statistics ?
...
for now there is few open issues re that.
lets specify and agree on the spec before that...

**Comment by A-Zak** [comment]
Also add from #180 :
It would be convenient to have running totals of queued, preboosted, boosted proposals (boostedProposalCount? etc)

**Comment by A-Zak** [comment]
@orenyodfat 
The stats that we need to display in alchemy are:

- Monthly active users (active = sent any tx)
    - I imagine this can be done by storing the last activity of an address and then only querying for the count of addresses with last activity greater than 1 month ago
- Monthly new proposals
    - This should be possible to query now, right?
- Monthly GEN staked
    - it would be nice to be able to break it down into three groups: upStake, downStake & daoDownStake.

Coming from #180, it would also help to have running totals for the current number of proposals in each state (queued, pre-boosted, boosted proposals (boostedProposalCount? etc))

**Comment by orenyodfat** [comment]
`monthly` it will be difficult to achieve as the query are from already indexed info.
also it will be nice to give it flexibility for any period. so lets call it **timed statistics**
I guess the **timed** statistics can be done on the client side much easly .

**Comment by A-Zak** [comment]
I agree, but we still need the subgraph to index the data to query... :)
Also, monthly active users is actually a **high priority task**. we need this in order to monitor our KPIs and improve on them.
please try to get to it sooner rather than later... :)

**Comment by ben-kaufman** [comment]
Closing this for now. If there's still relevant issue here please open a new issue.
