### ISSUE TITLE
Push docker images and npm package on CI

### ISSUE THREAD

**Issue by tsuberim** [daostack/subgraph#17]

**Comment by orenyodfat** [comment]
@tsuberim is that already addressed ?

**Comment by tsuberim** [comment]
Not on CI.

**Comment by jellegerbrandy** [comment]
We can adapt the `release.sh` script from the migration repo to do a similar thing. 

In fact, this means publishing the **postgres** image to docker hub, not the graph-node image. 

About naming, we can use the same naming convention as proposed on https://github.com/daostack/devops/issues/2, so the docker images would be called 

`@daostack/subgraph-postgres:ganache-0.0.1-rc11-v3-0.0.1-rc.9`
