### ISSUE TITLE
add more fields on `gpQueue` object

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#180]

**Comment by jellegerbrandy** [comment]
I'd liek to use the `gpQueue` object as the object on which the queues in alchemy are based on. For that, we need some additional fiedls on the gpQueue object:

- add `thresholdConst` to `gpQueue` object (and remove it from Proposal entity)
- In practice, we will have one scheme per queue, and (for now) at most 3 schemes (cf. #182). Even if  is in theory possible to have different schemes that use the same queue, we should consider simplifying our data model and at a `Scheme` property on the gpQueue object
- It  would be convenient to have running totals of queued, preboosted, boosted proposals (`boostedProposalCount`? etc)

**Comment by orenyodfat** [comment]
How about moving all genesis protocol params to gpQue :

```
	# Genesis Protocol params
	queuedVoteRequiredPercentage: BigInt!
	queuedVotePeriodLimit: BigInt!
	boostedVotePeriodLimit: BigInt!
	preBoostedVotePeriodLimit: BigInt!
	thresholdConst: BigInt!
	limitExponentValue: BigInt!
	quietEndingPeriod: BigInt!
	proposingRepReward: BigInt!
	votersReputationLossRatio: BigInt!
	minimumDaoBounty: BigInt!
	daoBountyConst: BigInt!
	activationTime: BigInt!
	voteOnBehalf: Bytes!
```

**Comment by orenyodfat** [comment]
re the stats : 
`It would be convenient to have running totals of queued, preboosted, boosted proposals (boostedProposalCount? etc)`

lets have #168 specified first

**Comment by orenyodfat** [comment]
lets split the statistic feature from this issue. 
so we can have it separately as it related to #168. @jellegerbrandy

**Comment by A-Zak** [comment]
I will move the convenience methods to #168

**Comment by jellegerbrandy** [comment]
#168 is about DAO stats, this is about the statistics of the Queue itself. They do not need more documentation, afaic, look at this picture: https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5c4de2b14def2a015bb1f59f

So we need to add running totals of
*  queued
* preboosted
* boosted proposals (boostedProposalCount

**Comment by jellegerbrandy** [comment]
We also need a way to distinguish between the different gpQueue objects and relate them to the schemes being used. Adding the same scheme property from https://github.com/daostack/subgraph/issues/182 (with the same values) to the gpQueue object would work.

**Comment by orenyodfat** [comment]
> #168 is about DAO stats, this is about the statistics of the Queue itself. They do not need more documentation or specs, afaic, look at this picture: https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5c4de2b14def2a015bb1f59f
> 
> So we need to add running totals of
> 
> * queued
> * preboosted
> * boosted proposals (boostedProposalCount

it is not clear to me.
