### ISSUE TITLE
Track various token balances for DAOs

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#181]
Specifically we want to know the balances for the following tokens:

"GEN": "0x543ff227f64aa17ea132bf9886cab5db55dcaddf"
        "DAI": "0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359"
        "GUSD": "0x056fd409e1d7a124bd7017459dfea2f387b6d5cd"
        "PAX": "0x8e870d67f660d95d5be530380d0ec0bd388289e1"
        "TUSD": "0x0000000000085d4780B73119b644AE5ecd22b376"
        "USDC": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
        "USDT": "0xdac17f958d2ee523a2206206994597c13d831ec7"

**Comment by orenyodfat** [comment]
why ?

**Comment by ben-kaufman** [comment]
This is impossible because of the sync time, you can't index all of that...

**Comment by orenyodfat** [comment]
Well, it might be possible using the dynamic adding contract feature or by having other subgraphs for each token. 
Though first lets discuss the why.

**Comment by jellegerbrandy** [comment]
I assume the need for this is to show the DAO balances for these tokens. 
We can get them directly from ethereum, no need to pass through the subgraph.
