### ISSUE TITLE
new subgraph image 0.6.0 does not support query syntax that we are using

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#183]
We are using a fairly large number of queries that use filters that not documented or explicitly defined in the graphql model.

Basically, for entities of the form: 
```
{ foo 
    { bar: { id : "1234" } }
 }
```
We are using queries like:

```
{ foo 
    (where: { bar: "1234" })
    { bar: { id : "1234" } }
 }
```

This worked, but is not workign aymore int he new graphnode 0.6.0 image. 

These queries are of two kinds. Most of them use filters for `dao` and `proposal` values, like the example below. 
```
 {
            proposalStakes (where: {
              proposal: "0x484bfd4ed9a0b92ce8928ac4aaab5bd2e1441a2d95f4fe72e214e6366d801852"
            }) {
              id
              createdAt
              staker
              proposal {
                id
              }
              outcome
              amount
            }
          }
```
Most (perhaps all) of these queries can be rewritten in the following form 
```proposal(id: "0x...") { stakes {... }}``` 

Another query we use is to distinguish different types of proposals like this one to get all ContributionReward proposals:
```
    {
            proposals(where: {
              stage: "Boosted"
    dao: "0xe7a2c59e134ee81d4035ae6db2254f79308e334f"
    contributionReward_not: null
            }) {
              id
              dao {
                id
              }
            }
          }
```
These queries can be rewritten in correct queries by resolving #182 

Before doing these rewrites, I'd like to hear @orenyodfat  or @ben-kaufman opinions.

**Comment by Jannis** [comment]
Ok, yeah, I see the problem. The fields you're filtering by are relationship fields, not regular string/address/bytes fields. These store ID strings but really their values are the referenced entities. Filtering with `where: { other: "some id" }` therefore doesn't work.

I think we have two options:

1. Allow filtering with `where: { other: { id: "some id" } }`
2. Allow filtering with `where: { other: "some id" }`

If GraphQL supports union types in input objects, we may even be able to do both.

The singular reference field is simple. Plural fields are little less obvious. Matching against a collection of relationships with `where: { others: ["some id", "other id"] }` seems straight forward, `where: { others: [ { id: "some id", ... }, { id: "other id", ... } ]}` raises the question what we do if multiple attributes are provided for the matches in `others`. But through typing, we could restrict `others` to be an array of objects with only `id` values.

**Comment by Jannis** [comment]
We can improve this in Graph Node. Until that lands, using
```
proposal(id: ...) {
  stakes { ... }
}
```
instead of
```
proposalStakes(where: { proposal: ... }) {
  ...
}
```
is a good solution,
