### ISSUE TITLE
Queue statistics

### ISSUE THREAD

**Issue by orenyodfat** [daostack/subgraph#191]
copy paste from #180 : 

#168 is about DAO stats, this is about the statistics of the Queue itself. They do not need more documentation or specs, afaic, look at this picture: https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5c4de2b14def2a015bb1f59f

So we need to add running totals of

queued
preboosted
boosted proposals (boostedProposalCount

@jellegerbrandy could you please put more light on that ?

**Comment by jellegerbrandy** [comment]
https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5c4de2b14def2a015bb1f59f

![image](https://user-images.githubusercontent.com/1306173/56277128-07322100-6104-11e9-96c0-faa111077cb4.png)


The `gpQueue` object is representing as in the above image in Genesis.

So we need to know how many queued, preboosted and boosted proposals there are.

We can count them, but for that we need to fetch them all. So instead, it would be good if the subgraph counted them for us. And this could be done by adding properties to the gpQueueu entity liek this:

`gpQueue.queuedProposalCount`
`gpQueue.preboostedProposalCount`
`gpQueue.boostedProposalCount`

(I have not particular preference fot he data model to use)

**Comment by ben-kaufman** [comment]
I don't remember what happened with the implementation of this issue exactly, but I'm pretty sure we decided not to do it on the subgraph side. Please reopen if still relevant.
