### ISSUE TITLE
include dutchX contract in the docker image

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#194]
For testing, it would be good to have the dxDAO deployed on ganache as it will be on main net

**Comment by orenyodfat** [comment]
ithis issue belong to migration repo .subgraph has nothing to do with that .
I am even not sure we should have this specific dao support on our repo
migration .
We can produce a ganache image per dao which is not part of the repo .this
can be done by a script which is part of the repo .
Let’s move the discussion to the migration repo

**Comment by jellegerbrandy** [comment]
https://github.com/daostack/migration/issues/124
