### ISSUE TITLE
quietEndingPeriodBeganAt not getting updated on new votes

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#199]
When someone votes during the Quiet Ending Period, the quietEndingPeriodBeganAt field is not getting updated

**Comment by orenyodfat** [comment]
Pr #200 already been merged though :
1. There is no test to confirm that.
2. There is no need to call the block chain twice upon voting event .
The state of the proposal should be get at updateproposal function at proposal.ts

**Comment by orenyodfat** [comment]
fix by #201
