### ISSUE TITLE
paramsHash in gpQueue is not the same as that in Scheme

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#205]
[try this query](https://subgraph.daostack.io/subgraphs/name/v15/graphql?query=%20%20%20%20%20%20%20%20%20%20%7B%20%20gpqueues%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20scheme%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20paramsHash%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20paramsHash%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D)

Not sure how the "gpQueue" paramsHash can differ from the scheme - I expected these to be the same object, basically...

**Comment by orenyodfat** [comment]
gqpue entity ,identified by the organisationid, cannot hold params and paramshash  . the params and params hash should be per proposal.
