### ISSUE TITLE
members collection is populated with addreses that have 0 rep and 0 tokens

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#208]
Got here playing around with alchemy and passing around rewards, so i do not have precise steps to reproduce. I find this in the collection.

What I expect is that all members either have a > 0 tokens or > 0 reputation.

![image](https://user-images.githubusercontent.com/1306173/56957074-47eb5a80-6b46-11e9-8da3-a38a69b82a39.png)
![image](https://user-images.githubusercontent.com/1306173/56957105-5cc7ee00-6b46-11e9-8b40-493536e8ebda.png)

**Comment by jellegerbrandy** [comment]
Actually, the last two records are also in the v16 docker images. So it should be easy to reproduce :-)

**Comment by ben-kaufman** [comment]
This is no bug, this is the Avatar. Though this part does need some small refactoring but it's not related.
You requested in the past to have the Avatar as a member, I can remove that but I guess you do need it.

**Comment by jellegerbrandy** [comment]
Okay, we are indeed using that. Sorry for the confusion.
And the first record with the NULL address?

**Comment by tibetsprague** [comment]
Wait, why do we want to show the avatar as a "member", thats confusing.

**Comment by ben-kaufman** [comment]
@jellegerbrandy couldn't reproduce that 0 address, can you give some details on how you created that?
