### ISSUE TITLE
Improve ReputationContract <-> ReputationHolder Entity Linking 

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/subgraph#211]
Currently, ReputationContract & ReputationHolder are defined like so:
```graphql
type ReputationContract @entity {
	id: ID!
	address: Bytes!
	totalSupply: BigInt!
	reputationHolders: [String!] // maps to ReputationHolder.id
}

type ReputationHolder @entity {
	id: ID!
	contract: Bytes! // maps to ReputationContract.address
	address: Bytes!
	balance: BigInt!
}
```
Which makes querying for all reputation holders of a given reputation token difficult as it requires multiple queries and an intermediate step. In an ideal scenario, we would be able to query like so:
```graphql
{
  reputationContracts {
    id
    address
    reputationHolders {
      id
      address
      balance
    }
  }
}
```

I can see this same pattern is used for [TokenContract & Token Holder](https://github.com/daostack/subgraph/blob/da5388863c385cfe35a3e455a6c3c8bddcc7e181/src/mappings/DAOToken/schema.graphql#L1-L14), so I might be missing some reasoning behind implementing it this way.

**Comment by dOrgJelli** [comment]
I believe the new schema would look something like:
```graphql
type ReputationContract @entity {
	id: ID!
	address: Bytes!
	totalSupply: BigInt!
	reputationHolders: [ReputationHolder!]
}

type ReputationHolder @entity {
	id: ID!
	contract: ReputationContract!
	address: Bytes!
	balance: BigInt!
}
```

**Comment by orenyodfat** [comment]
I agree that this might be more optimise. . though I  am not sure there is a need for  that as
querying  daos members can be done using members field under dao entity 
https://github.com/daostack/subgraph/blob/master/src/domain/schema.graphql#L19

**Comment by dOrgJelli** [comment]
Understood. This conversation is related to the thread here: https://github.com/daostack/client/pull/191

If that PR is closed, then we can close this issue as well, and the standard way of accessing reputation will be through the DAO.
