### ISSUE TITLE
add a scheme --> gpQueue edge

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#217]
We already have `gpQueue.scheme`;  what we really need is the inverse `controllerscheme.queue` edge.

**Comment by jellegerbrandy** [comment]
as a remark: this will simplify the "create a dummy queue object in the client for known schemes that do do not have a gpqueue yet in the subgraph". But I realized working on it that my solution in the client is not very scaleable (once we have many daos and we can add new schemes to the index dyanmically), so I think that in the long run we will have to find a solution for this in the subgraph after all...

**Comment by orenyodfat** [comment]
Not sure , as not all controller schemes as ques .

**Comment by jellegerbrandy** [comment]
Those schemes would have queue set to null.

**Comment by orenyodfat** [comment]
so all schemes will have queue set to null upon registration to the controller and when the queue will be created (first proposal ) there queue will be created ?
