### ISSUE TITLE
"Null value resolved for non-null field `scheme`"

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#221]
running this queyr on v17 on rinkeby I get a "Null value resolved for non-null field `scheme`" error

```
 { proposal(id: "0xe2a45acff36ce9bf024889f1ea6408d8c030121144b9a89107ba1e6ed7bfa1c3") {
  id 
  scheme {id}
}}
```

here's the link:
https://rinkeby.subgraph.daostack.io/subgraphs/name/v17/graphql?query=%20%7B%20proposal(id%3A%20%220xe2a45acff36ce9bf024889f1ea6408d8c030121144b9a89107ba1e6ed7bfa1c3%22)%20%7B%0A%20%20id%20%0A%20%20scheme%20%7Bid%7D%0A%7D%7D

**Comment by orenyodfat** [comment]
the reason for that is that someone proposed and execute a proposal to remove the contribution reward scheme from the test fastdao . 
when scheme is removed its ControllerScheme entity is removed as well.

see [proposal to remove ](https://rinkeby.subgraph.daostack.io/subgraphs/name/v17/graphql?query=%20%7B%20proposal(id%3A%220x20463b1c06f716ace6e1b31ef226a25a726fefc24fd5deaa35d67888ee2821cc%22)%20%7B%0A%20%20schemeRegistrar%20%7B%0A%20%20%20%20id%0A%20%20%20%20schemeRemoved%0A%20%20%20%20schemeToRemove%0A%20%20%20%20%0A%20%20%7D%0A%20%20proposer%0A%20%20executionState%0A%7D%7D)

- we should update this scheme field on the proposal to be able to be null.
