### ISSUE TITLE
set `proposal.schemeRegistrar.schemeRegistered` to true if the scheme is registered

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#223]
If I create a new proposal use `SchemeRegistrar.proposeScheme` for a schema that is already registered, I expect to find a proposal object with `proposal.schemeRegistrar.schemeRegistered === true`

**Comment by jellegerbrandy** [comment]
This is useful for alchemy to be able to distinguish between editing and adding a proposal (which for the rest use the same function calls)

**Comment by orenyodfat** [comment]
Does the daos schemes or controllerschemes are not good enough to detect already registered schemes?

**Comment by jellegerbrandy** [comment]
Well yes of course, but 

1. that means we need two queries to get the proposal data we need (one for the proposal entity, one for the dao.schemes). 

2. apart fromt he intended usage, it seems to me that this is a subgraph bug in any case. What does `schemeRegistered` **mean** if it does not mean that the scheme is registered?

**Comment by jellegerbrandy** [comment]
Actually, I take (1) back. We can do ```
  {
    proposals {

      dao {
        id
        schemes {
          id
        }
      }
    }
    }
``` 
to get the schemes of the dao of the proposal.

**Comment by orenyodfat** [comment]
״apart fromt he intended usage, it seems to me that this is a subgraph bug in any case. What does schemeRegistered mean if it does not mean that the scheme is registered?״

schemeRegistered means that the register scheme proposal was executed successfully. (scheme on the proposal is now registered)
schemeRemoved    means that the remove scheme proposal was executed successfully. (scheme on the proposal is now not registered)
