### ISSUE TITLE
we need a way to get the target contract of a genericScheme from the scheme itself

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#240]
What we'd like to do in Alchemy: show the address of the contract that will be called before actually creating the proposal - for example, to show the dutchX forms, we need to know that this GenericScheme is calling the dutchx contract.

As far asI can see, this info is not available in the subgraph at the moment.

I am not sure what the best place to store it is....

**Comment by orenyodfat** [comment]
Does the address of the target generic call is enough ? Or u need also the
name ?

**Comment by jellegerbrandy** [comment]
The address is enough
