### ISSUE TITLE
create docker images with the base contracts already indexed

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#241]
At themoment, the docker images of https://hub.docker.com/r/daostack/subgraph-postgres/tags have snapshop of the database **before** the contracts are being indexed. This means that when starting up the docker containers for development and testing, we need to wait until all events are indexed.

This was not a problem previously, because it was very quick (a few seconds). With the large amount of new contracts being indexed, this is becoming cumbersome, both in terms of development cycles as well as bookkeeping in the tests...

Please creathe the postgres image of the postgres db **after** it is done indexing...

**Comment by ben-kaufman** [comment]
This means we either put a long sleep (like 5 minutes or so) in the script (which isn't that bad as it is only used for releases). Or we need to listen to the subgraph from the script to know when the status is synced, which I'm not sure how to do (or if that's possible with bash...). Do you think just adding sleep will be good enough here?

**Comment by ben-kaufman** [comment]
This issue was handled in the `test-env` repo, closing here.
