### ISSUE TITLE
order proposals by "closing time"

### ISSUE THREAD

**Issue by dkent600** [daostack/subgraph#255]
we need to be able to sort boosted & pre-boosted proposals by "closing time".  This value is calculated according to the following code take from Alchemy:

```
export const closingTime = (proposal: IProposalStateFromDaoStackClient) => {
  switch (proposal.stage) {
    case IProposalStage.ExpiredInQueue:
    case IProposalStage.Queued:
      return moment((proposal.createdAt + proposal.queuedVotePeriodLimit) * 1000);
    case IProposalStage.PreBoosted:
      return moment((proposal.preBoostedAt + proposal.preBoostedVotePeriodLimit) * 1000);
    case IProposalStage.Boosted:
      return moment((proposal.boostedAt + proposal.boostedVotePeriodLimit) * 1000);
    case IProposalStage.QuietEndingPeriod:
      return moment((proposal.quietEndingPeriodBeganAt + proposal.quietEndingPeriod) * 1000);
    case IProposalStage.Executed:
      return moment(proposal.executedAt * 1000);
  }
};
```

**Comment by orenyodfat** [comment]
This already been discussed and agreed that this should be calculated in
the client side

**Comment by dkent600** [comment]
@orenyodfat  If we are to support paging when sorting, then my understanding is that this needs to be computed in subgraph.

**Comment by orenyodfat** [comment]
it cannot as the subgraph do not have timer and there is no event when the proposal closed.

**Comment by orenyodfat** [comment]
see https://github.com/daostack/subgraph/issues/93 for discussion

**Comment by A-Zak** [comment]
@orenyodfat We need this to come from the subgraph now.
Like Doug said, because of the pagination / sorting combination, there is no other way (see #256).

What do you mean by "doesn't have a timer"?

**Comment by dkent600** [comment]
@orenyodfat I am thinking that all subgraph has to do is maintain the "closed" state as best it can based on the various events that indicate it may have changed.   Alchemy already accepts that this state is not guaranteed except immediately after calling `execute`.

@A-Zak   @jellegerbrandy @ben-kaufman
