### ISSUE TITLE
index thedxDAO DAO on rinkeby

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#261]
not "really" the dxDAO (in the sense that the generic scheme does not call the dutchX contract), but a DAOthat is called "dxDAO" and that has a genericScheme.

As I understand it, such a DAO is already deployed, it just needs to be added to the index https://rinkeby.subgraph.daostack.io/subgraphs/name/v20/graphql?query=%7B%0A%20daos%20%7B%0A%20%20name%0A%20%20id%0A%20%20%0A%7D%0A%7D

**Comment by ben-kaufman** [comment]
I need the DAO info in order to add it. Can you please send it here?

**Comment by orenyodfat** [comment]
http://ec2-3-19-3-204.us-east-2.compute.amazonaws.com:8800/subgraphs/name/v20/graphql?query=%7B%0A%20%20daos%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A

though this is without separate ipfs .

how this issue is related to this repo ?
