### ISSUE TITLE
"accountsWithUnclaimedRewards" contains addresses that have no rewards to claim

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#263]
The proposal linked below has no more GP rewards to claim (`proposal.rewards = []`) and has no contributionrewards to claim either , because it was not accepted.

However, the `accountsWithUnclimedRewars` list is empty.

https://rinkeby.subgraph.daostack.io/subgraphs/name/v20/graphql?query=%7B%0A%20proposals%20(where%3A%20%7B%20id%3A%20%220x9368dc0d7ab63038a556ca718c230cb3d0f4bfd2c21a7401aed3c68c263656bf%22%20%7D)%20%7Bid%20%0A%0Atitle%0A%20%20dao%20%7Bname%7D%0A%20%20stage%20%0A%20%20executionState%0AwinningOutcome%0A%20%20accountsWithUnclaimedRewards%20%0A%20%20gpRewards%20%7B%0A%20%20%20%20beneficiary%0A%20%20%7D%0A%7D%0A%7D

**Comment by ben-kaufman** [comment]
@jellegerbrandy This is because the `accountsWithUnclimedRewars` also includes the ContributionReward beneficiary, which as you can see did not redeem his reward.

**Comment by jellegerbrandy** [comment]
can you please re-reread my description :-)

the proposal is NOT ACCEPTED, so there are no mor rewards to claim.

**Comment by ben-kaufman** [comment]
Yeah, my bad, I pushed a PR to fix it.
