### ISSUE TITLE
use the daoregsitry contract to register the daos

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#271]
https://subgraph.daostack.io/subgraphs/name/v20/graphql?query=%7Bdaos%20%7Bname%20register%20%7D%7D : it is all "na"

**Comment by orenyodfat** [comment]
please confirm that it works on staging : 
https://rinkeby.subgraph.daostack.io/subgraphs/name/v20/graphql?query=%7B%0A%20daos%20%20%7B%0A%20%20name%0A%20%20register%0A%20%20id%0A%7D%0A%7D

**Comment by jellegerbrandy** [comment]
works!

**Comment by jellegerbrandy** [comment]
about the question of where to register the daos (in the subgraph, or in the client and alchemy test environments): thinking about it, the migration is the best place, because otherwise we need to implement a  "register the daos" step in different places:
- before testing the client
-before  running the tests in alchemy
- as part of the setup of the development environment for alchemy

So better do in in migration, if that's ok.

**Comment by orenyodfat** [comment]
Does this issue belongs here or migration repo?
Is that related only for ganache ?

**Comment by jellegerbrandy** [comment]
yes, see https://github.com/daostack/migration/issues/149
