### ISSUE TITLE
reclaiming your stakes for proposals that are expired in the Queue

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#273]
When proposals expire in the Queue without a decision, the stakers can claim their stake back. In  Alchemy, this means showing the proposals in the redemptions page, and treating them just as the other Executed proposals.

However, these proposals will typically not have the staet `ExpiredInQueue` on-chain - they will simply be `Queued`. And in the subgraph, the `gpRewards`, which we use to calculate how much the user can claim back, will be empty. Also, `accountWithUnclaimedRewards` will be empty, so the proposal wil not show up inthe user's rewards page.

Not sure what the best way to approach this is. We set `gpRewards` always to the stakes of the user (and add each staker to the `accountswithunclaimedrewards`)  on each staking event, and be careful to filter correctly on the client side.

I personally think a better solution would be to have the subgraph update the expried proposals on each  "tick" (each new block) with the relevant data, so we would have to do no ad hoc filtering client side to work around this...

**Comment by orenyodfat** [comment]
proposals are queued till it is executed.

**Comment by jellegerbrandy** [comment]
@ben-kaufman has added this execution step to the bot, so we should get the results automagically
