### ISSUE TITLE
ssl cert expired on https://rinkeby.subgraph.daostack.io/

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#277]

**Comment by ben-kaufman** [comment]
This issue is not related to this repo so I don't think it should be here...

**Comment by jellegerbrandy** [comment]
I agree but where should it be instead?

**Comment by jellegerbrandy** [comment]
in any case, this is resolved. The reason (and the important takeway for next time) is that someone firewalled port 80, which made certbot fail on trying to renew the certificate.
