### ISSUE TITLE
support for `OR` operators

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#279]
ín the alchemy history page we concatenate the results of these two queries: 
```
proposals {where: { stage_in: [IProposalStage.ExpiredInQueue, IProposalStage.Executed] } ...
```
```

proposals {where:  { stage: IProposalStage.Queued, expiresInQueueAt_lte: Math.floor(new Date().getTime() / 1000) }
```

The fact that these are two different queries makes sorting and paging very hard to implement, so we'd like to have one single query

**Comment by jellegerbrandy** [comment]
following orens suggestion and looking here https://www.howtographql.com/react-apollo/7-filtering-searching-the-list-of-links/ I have tried:

```
{ daos (where: { OR: [
  {id:"0x86072cbff48da3c1f01824a6761a03f105bcc697"},
    {id:"0x86072cbff48da3c1f01824a6761a03f105bcc697"}  
]
}) { id, name}
```  
  { name id 
}}

Which gives me a syntax error.

**Comment by jellegerbrandy** [comment]
This comment is relevant and probably applies to our situation as well: https://github.com/graphql/graphql-js/issues/585#issuecomment-262402544

**Comment by jellegerbrandy** [comment]
while this query gives me no error,b ut ti just ignores the filter: 
```
{ daos (filter: { OR: [
  {id:"0x86072cbff48da3c1f01824a6761a03f105bcc697"},
    {name: "Endemic Bunny"},
  
]}
)
  
  { name id 
}}
```

**Comment by jellegerbrandy** [comment]
There is a possible workaround for this, for this specific history query. 

we could run this query: 
```
{ proposals (
  where: { 
    stage_in: ["ExpiredInQueue", "Executed", "Queued"] ,
    expiresInQueueAt_lte: $currentDate
}) 
  
  { id expiresInQueueAt
    stage
}}
```
Currently, this will not work, bc we may have Executed proposals that are not past their `expiresInQueue` data. 
But if we chagne the subgraph, and set "expiresInQueueAt" to 0 (zero) for all proposals that are not `Queued`, this should give us exactly the proposals we want.

**Comment by orenyodfat** [comment]
does using closingAt field https://github.com/daostack/subgraph/blob/master/src/domain/schema.graphql#L59 will do the work. ?

**Comment by jellegerbrandy** [comment]
yesss
