### ISSUE TITLE
Need fields DAO.closedProposalsCount and Scheme.queuedProposalsCount

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#280]
We want to use lazy loading (infinite scrolling) for the DAO History and for a Scheme's Queued proposals, so that we don't overload the UI as the number of proposals grows. To do this Alchemy needs to know what the total count of queued proposals for a Scheme is and the total count of proposals in the History view. Here are the queries we are using which need to summarized into a count:

Scheme queued proposals: dao.proposals({ where: { scheme: schemeId, stage: IProposalStage.Queued, expiresInQueueAt_gt: Math.floor(new Date().getTime() / 1000) }})

Historical proposals: dao.proposals({
                where: {
                  stage_in: [IProposalStage.ExpiredInQueue, IProposalStage.Executed, IProposalStage.Queued],
                  closingAt_lte: Math.floor(new Date().getTime() / 1000)
                },

This is a problem because we are using time based queries, which means that the subgraph could never really have an accurate count of what we want to display on the front-end. Thoughts?

**Comment by jellegerbrandy** [comment]
Why do we need to know the total to implement infinite scrolling? We can just call "loadMore" until the results are finished (and the list could potentially be infinite)

**Comment by tibetsprague** [comment]
right
