### ISSUE TITLE
closingAt does not work as expeced

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#289]
the field would be much more useful for us if "closingAt" was set to the current time at the moment of execution.

see for a description of the problem here: https://github.com/daostack/alchemy/issues/901

**Comment by orenyodfat** [comment]
like executedAt ?

**Comment by jellegerbrandy** [comment]
Can you have a look at the issue I linked to? We've discussed the problem before: we need some way to get all expired/executed proposals with a single query. You suggested that using "closingAt" was the solution, but it turns out it is not. As far as I can see, there currently is no way to get the desired result from the subgraph.

**Comment by jellegerbrandy** [comment]
In other words, yes, we need some XXXAt fied that has the value of executedAt for executed proposals, and closingAt otherwise.

**Comment by ben-kaufman** [comment]
So you just need closingAt to have the value of executedAt after execution right?

**Comment by tibetsprague** [comment]
yes
