### ISSUE TITLE
Support the ReputationFromToken Scheme

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#294]
For https://daostack.tpondemand.com/RestUI/Board.aspx#page=board/5209716961861964288&appConfig=eyJhY2lkIjoiQjgzMTMzNDczNzlCMUI5QUE0RUE1NUVEOUQyQzdFNkIifQ==&boardPopup=feature/1320/silent

We need the list of beneficiaries and the reputationReward and i guess redeemEnableTime?

**Comment by orenyodfat** [comment]
This scheme is never been used

**Comment by orenyodfat** [comment]
And not sure why it need to be indexed

**Comment by jellegerbrandy** [comment]
We probablly do not need this to be indexed, at least not for the simple usage we are making of it.

**Comment by jellegerbrandy** [comment]
We do not need any code change in the subgraph, but we do need to have the instance of FixedReputationAllocation  (as deployed in [this issue](https://github.com/daostack/migration/issues/169)) as part of the `contractInfos` collection (so we can find the ABI, etc)

**Comment by orenyodfat** [comment]
There is no any dao using this scheme in the near future .

**Comment by tibetsprague** [comment]
@A-Zak says supporting this scheme in alchemy is high priority

**Comment by jellegerbrandy** [comment]
I changed the titel but realize the whole issue discussion now has become senseles.s I'll make a new issue :-)
