### ISSUE TITLE
keep older versions of the subgraph alive

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#321]
@dOrgJelli  notes in https://github.com/daostack/client/issues/287, 

"""
DAOcomponents continues to become broken when the subgraph endpoint changes, for example from v23 to v24.

How do you propose we remedy this issue? Here are some possible solutions:
* DAOcomponents host its own subgraph. This subgraph would run a version that's compatible with the version of the client library that DAOcomponents is currently using.
* DAOstack has a "service lifetime agreement" that states that all versions of the subgraph, once live, will be kept up for a minimum of 2 months. 
"""

**Comment by jellegerbrandy** [comment]
I'm strongly for jordans second solution.

**Comment by dOrgJelli** [comment]
Since we'll be moving to The Graph's hosting, will they solve this for us by keeping all versions online @orenyodfat?

**Comment by orenyodfat** [comment]
as long as we will deploy each version under a new name , I guess it will be kept on the the graph hosting.

**Comment by orenyodfat** [comment]
done with thegraph service
