### ISSUE TITLE
create member Id on the basis of dao address and user address

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#325]
So to make most efficiet use of the apollo cache, it would be convenient if the ID of the reputationholder was calculated as `crypto.keccak256(concat(daoAddress, owner)).toHex()` (instead of the current  situation,where the id is calculated on the basis of the reputationcontract address. 

It seems to me we can do this, as there is a 1-1 relation between daos and reputationcontracts.

**Comment by orenyodfat** [comment]
it is not so straight fwd as there are cases where the repHolder is created before the dao creation.
e.g   - by using the daocreator - first there is rep minting and after create the dao and attached the rep contract.

why it will make Apollo more efficient ?

**Comment by jellegerbrandy** [comment]
Ok., 

The apollo cache is organized around ids, we are having lots of queries where we get search for a rep holder based on her address + the dao address (ie.e. that look like `reputationHolder(where: { dao: daoAddress, address: owner})`), and those queries coudl access the cache directely if we could rewrite them as `reputationHolder(id: keccak256(daoAddres,owner)`
