### ISSUE TITLE
keep counts of proposals

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#326]
We are doing a lot of separate queries to count proposals, and we coudl avoid that if these counters are part of the index. So I'd like to add the folllowing fields:

``` 
Scheme.numberOfQueuedProposals
Scheme.numberOfPreBoostedProposals
Scheme.numberOfBoostedProposals
DAO.numberOfQueuedProposals
DAO.numberOfPreBoostedProposals
DAO.numberOfBoostedProposals
```
For the other states (`ExpiredInQueue`, `Executed`, `QuietEndingPeriod`) we are not doing separate queries, but it could be useful to have these counts available anyway to help us with paging and showing totals.

**Comment by jellegerbrandy** [comment]
We also need this because the current approach (getting all the proposals and counting them) will break if there are over 100.

**Comment by ben-kaufman** [comment]
Are you sure there's a need for both DAO and scheme support of the counting? You can count the schemes of a DAO to get the DAO count in the client with this query:
```
{
  daos {
    schemes {
      numberOfQueuedProposals
      numberOfPreBoostedProposals
      numberOfBoostedProposals
    }
  }
}
```

I can add for both but it's just a lot of replicated code and makes the codebase messy.
