### ISSUE TITLE
package is not require'able

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#33]
`require('@daostack/subgraph')`  gives an Error: `
Error: Cannot find module '@daostack/subgraph'
`

This presumably is because there is no ` "main"` invocation in  `package.json`.

**Comment by tsuberim** [comment]
What do you want the package to expose?

**Comment by jellegerbrandy** [comment]
It is not a very big deal, but I'm using the mgiration and deployment sripts in the `alchemy` repo, and I want to do things like: 

```
subgraphLocation = require.resolve('@doastack/subgraph')
configure = require(`${subgraphLocation}/ops/configure.js`)
```
So it does not need to expose anything in particular, just let me access the scrits more easily.
