### ISSUE TITLE
v28 is not indexing genericschemeParams

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#342]
Run this query: ```{ controllerSchemes (where: {name : "GenericScheme" }) {
  id name genericSchemeParams {
    id
  }
  dao { name }
}}```

On v28, this gives results where `genericSchemeParams` is `null`: https://thegraph.com/explorer/subgraph/daostack/v28_0 and https://thegraph.com/explorer/subgraph/daostack/v28_0_rinkeby

It works on the old versino: https://subgraph.daostack.io/subgraphs/name/v24/graphql?query=%7B%20controllerSchemes%20(where%3A%20%7Bname%20%3A%20"GenericScheme"%20%7D)%20%7B%0A%20%20id%20name%20genericSchemeParams%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%20%20dao%20%7B%20name%20%7D%0A%7D%7D

**Comment by jellegerbrandy** [comment]
More precisely: it si indexing the rc.27 version fine, but not the olders contract versions.

**Comment by orenyodfat** [comment]
please note that genericSchemeParams is for none universal generic schemes. (e.g in nectar Dao at https://thegraph.com/explorer/subgraph/daostack/v28_0_rinkeby).
uGenericSchemeParams is for universal generic scheme . 
regardless of the version.

**Comment by ben-kaufman** [comment]
As @orenyodfat said, you should use `uGenericSchemeParams` for the universal version, and `genericSchemeParams` for the non-universal version, regardless of the deployment version of the contracts. Query is working well when I do this, can I close this issue?

**Comment by orenyodfat** [comment]
already discussed that with @jellegerbrandy .
for now we will stay with alchemy "workaround" .
