### ISSUE TITLE
v28_0 is not indexing (all) ipfs data

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#343]
to see this, run this query 

```
{ proposals (orderBy: createdAt orderDirection:desc ){id title }}
```
[here](https://subgraph.daostack.io/subgraphs/name/v24/graphql?query=%7B%20proposals%20(orderBy%3A%20createdAt%20orderDirection%3Adesc%20)%7Bid%20title%20%7D%7D) and compare this to  [here](https://thegraph.com/explorer/subgraph/daostack/v28_0)

**Comment by orenyodfat** [comment]
sure, because the ipfs data is not synced. never got request for that.

**Comment by orenyodfat** [comment]
ipfs history synced.
