### ISSUE TITLE
numberOfQueuedProposals is 0 but a queued proposal exists

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#346]
With query ```{ proposals
  (where:{dao:"0xbe08030e687066fec4433f013953293167de68aa" }) 
  {id  title scheme { id name address numberOfQueuedProposals } stage }}```

on https://thegraph.com/explorer/subgraph/daostack/v28_0_rinkeby

result looks like this:
```
{
  "data": {
    "proposals": [
      {
        "id": "0x66dbcd61e464ba5fbf5e361eae7a251a2cfcfff771b066bffdd312b0afedb0c1",
        "scheme": {
          "address": "0x8ff49219e74e076cf4f1b244a47875d7009e2595",
          "id": "0x8874c654d7fd360a65c0d77518e667d381adbc4101888c90597c8039375d8b1b",
          "name": "ContributionReward",
          "numberOfQueuedProposals": "0"
        },
        "stage": "Queued",
        "title": "hello"
      }
    ]
  }
}
```
note how stage is queued, but numberofqueuedproposals is 0

**Comment by orenyodfat** [comment]
only on rinbkey

**Comment by ben-kaufman** [comment]
Running this query I don't see the issue. There are 2 queued proposals and this is what the numberOfQueuedProposals returns as well. Can I close this issue?

**Comment by jellegerbrandy** [comment]
it was fixed with the latest updat
