### ISSUE TITLE
new feature: tags

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#354]
We are introducing tags in alchemy - basically a many-to-many relation between proposals and tag names.

We will implement this by:

- saving tags as a list on the ipfs "description", which will look like:
` ` `
{
title: "some tittle" ,
description: " ...." ,
tags: ["tag1" , " tag2" , "tag2" ]
}` 
- for the UI, we need to be able to: (a) list the tags with each proposal (b) get the complete list of tags and (c) search for proposals by tag

These data need to be indexed by the subgraph The most straightfoward solution seems to be:

- have a new `Tag` entity with attributes `id`  and `name` (or we can even use the ` name` as the id)
- add a property `tags`  to the Proposal entity, which refres to a list of Tag instances

**Comment by orenyodfat** [comment]
so a proposal json will include `tags` field along with `title` and `description` ? 
the proposer will add these tags along the `title` and `description` ?

**Comment by jellegerbrandy** [comment]
yes

**Comment by orenyodfat** [comment]
is this fixed yet ?
