### ISSUE TITLE
on rinkeby subgraph, proposal title and description are not updated

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#358]
We use these settings (same as on production, where it works)
```
    ipfsProvider: process.env.ARC_IPFSPROVIDER || {
      "host": process.env.ARC_IPFSPROVIDER_HOST || "api.thegraph.com",
      "port": process.env.ARC_IPFSPROVIDER_PORT || "443",
      "protocol": process.env.ARC_IPFSPROVIDER_PROTOCOL || "https",
      "api-path": process.env.ARC_IPFSPROVIDER_API_PATH || "/ipfs-daostack/api/v0/",
    },

```

**Comment by orenyodfat** [comment]
please send an example.
this proposal which was created yesterday looks updated
https://alchemy-staging-rinkeby.herokuapp.com/dao/0x72939947e7a1c4ac94bb840e3304b322237ad1a8/proposal/0xf931465f94084ff8daea5eb5e59ff0cf61d5714a5514e9d65f161c6d0b4264f4

**Comment by jellegerbrandy** [comment]
if you run this query on https://thegraph.com/explorer/subgraph/daostack/v29_0_rinkeby, you'll see that there are many proopsals with a descriptionHash set but no title or description: `{ proposals { title id description descriptionHash }}`

I do not manage to access the Ipfs instance directly via curl for some reason, so I cannot check if the data are actually there.

**Comment by jellegerbrandy** [comment]
Ok, this is because the ipfs historical data are not available on rinkeby, so no bug
