### ISSUE TITLE
controllerSchemes not updated

### ISSUE THREAD

**Issue by shivgupt** [daostack/subgraph#364]
The `genericSchemeParams` does not get updated in `controllerSchemes`

Details:
**Cashed data:** Scheme params for the given DAO as stored by subgraph is [this](https://rinkeby.subgraph.daostack.io/subgraphs/name/v26/graphql?query=%7B%20%0AcontrollerSchemes(%0A%20%20where%3A%20%7B%0A%20%20%20%20name%3A%20%22GenericScheme%22%2C%0A%20%20%20%20dao%3A%20%220x3cdb39c1ca57c19a316dd2f5acf900705220c713%22%0A%20%20%7D%0A)%7B%0A%20id%0A%20%20genericSchemeParams%7B%0A%20%20%20%20id%0A%20%20%20%20votingMachine%0A%20%20%20%20contractToCall%0A%20%20%20%20voteParams%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20dao%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D%0A%7D)

**Alchemy Info:** ParamHash registered for this Generic scheme for the same DAO is [this](https://alchemy-staging-rinkeby.herokuapp.com/dao/0x3cdb39c1ca57c19a316dd2f5acf900705220c713/scheme/0x1280a472af9e96859f629f7e263b95b498a6619dc32bcf849c64821d4233b087/info/)

**Etherscan values:**  When we read parameters for hash - 0x1e117425cc51d2d176ab6d66b62cd10e405bc66fe4ddac812b3d177d6f83f185

We get:
intVote:  0xe3692ad4ed2d2817bea59aed435ce17d28e884eb
voteParams:  0xcb8fd5df7487151fe7dd8632dbca1590c9b0333fcda1026ca51dac2dd96a52af
contractToCall:  0x38f1886081759f7d352c28984908d04e8d2205a6

**passed proposal** to update paramHash from `0x1e69cb6d08b28e66b0e894d6b40d8060ac9417d91b71d7dcf079f03f7210d6cd` to `0x1e117425cc51d2d176ab6d66b62cd10e405bc66fe4ddac812b3d177d6f83f185`, can viewed from history [here](https://alchemy-staging-rinkeby.herokuapp.com/dao/0x3cdb39c1ca57c19a316dd2f5acf900705220c713/proposal/0xa6adc1cfd9e59afc0d8470b179cda6e3524c1f1982019b2f883b77601f8a3d77)

**Comment by shivgupt** [comment]
Also,

Subgraph shows null genericSchemeParams for the other DAO [here](https://rinkeby.subgraph.daostack.io/subgraphs/name/v26/graphql?query=%7B%20%0AcontrollerSchemes(%0A%20%20where%3A%20%7B%0A%20%20%20%20name%3A%20%22GenericScheme%22%2C%0A%20%20%20%20dao%3A%20%220x15f83af955187b40b9a9a6e734b23ca5a50c36dd%22%0A%20%20%7D%0A)%7B%0A%20id%0A%20%20genericSchemeParams%7B%0A%20%20%20%20id%0A%20%20%20%20votingMachine%0A%20%20%20%20contractToCall%0A%20%20%20%20voteParams%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20dao%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D%0A%7D)

While the proposal to register GenericScheme passed: [proposal](https://alchemy-staging-rinkeby.herokuapp.com/dao/0x15f83af955187b40b9a9a6e734b23ca5a50c36dd/proposal/0x664e8ddef977c0a5f2d6cf2d2551550216dd7323d2fc1aa4a6fa3f1733b6aaf4)

A caveat here is that, in both cases write to genericScheme `setParameters`  was made after the proposal passed.

**Comment by orenyodfat** [comment]
@shivgupt the subgraph updating(read) the scheme params upon a schemeRegister event .
if the params set after the proposal passed (scheme registered) the subgraph will include wrong genericSchemeParams . this need to be documented somewhere.

 - please also note that you should use rinkeby subgraph as alchemy staging is using ( (https://thegraph.com/explorer/subgraph/daostack/v29_0_rinkeby ). 

- please note that this Dao is based on old arc version (rc.19) . so the generic scheme is a universal one.
  the query should be

```
 { 
controllerSchemes(
  where: {
    name: "GenericScheme",
    dao: "0x3cdb39c1ca57c19a316dd2f5acf900705220c713"
  }
){
 id
  paramsHash
  uGenericSchemeParams{
    id
    votingMachine
    contractToCall
    voteParams{
      id
    }
  }
  dao {
    id
  }
}
}

```

**Comment by orenyodfat** [comment]
try to re register the scheme (**after** setParameters) and all will be fine

**Comment by orenyodfat** [comment]
@shivgupt can we close this issue ?

**Comment by shivgupt** [comment]
Oops yeah, It worked!..closing.
