### ISSUE TITLE
add Tag.proposals and Tag.numberOfProposals

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#365]
Can we extend the Tags entity with the following properties?

- `Tag,proposals` 
- `Tag.numberOfProposals`

**Comment by orenyodfat** [comment]
please be more clear on this request .
what is Tag.proposals ? 
Does Tag.numberOfProposals is the number of proposal this tag is appears on ?

**Comment by jellegerbrandy** [comment]
Tag.proposals are the proposals that the tag is used for, it is the inverse of the Proposal.tags relationship you already defined.

And yes, the number of proposals is a counter of these proposals, so we do not have to fetch the whole list of proposals to know how often a tag has been used.
