### ISSUE TITLE
numberOfBoostedProposals is -1

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#371]
numberOfBoostedProposals is -1, which is obviously wrong.

Run this query: 

```
{
  daos (where: {id: "0x0b93ba560283350d4216f29dc57e15df38d0eace"}) {
    id
    schemes {
      id
      numberOfBoostedProposals
    }
  }
}
```
on mainnet graph (for example here: https://thegraph.com/explorer/subgraph/daostack/v29_0)

**Comment by orenyodfat** [comment]
not fixed yet.
#374 suppose to fix it

**Comment by jellegerbrandy** [comment]
hey oren, this cannot be fixed in alchemy until it is deployed. So I'm re-opening this, if you don't mind :-)

**Comment by orenyodfat** [comment]
the issue is fixed .
deploying the subgraph and alchemy readiness is another issue.
