### ISSUE TITLE
Add scheme property to event entity 

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#399]
Users can follow specific schemes to see all events for proposals in that scheme, so to be able to query for events by scheme address we need a scheme field added to events.

**Comment by orenyodfat** [comment]
Are you looking for a query to get all proposals ,votes and stakes for
 specific scheme ?

**Comment by tibetsprague** [comment]
yes, we need to query for all events connected to a specific scheme. so I assume that means all the events associated with proposals from that scheme: ProposalStageChange, VoteFlip, NewProposal, Stake, Vote. At least thats what I assume @A-Zak intended by following a Scheme

**Comment by orenyodfat** [comment]
Why is that needed ?

**Comment by tibetsprague** [comment]
i already explained, people can follow schemes in Alchemy, in which case their feed is supposed to show all events associated with that Scheme.

**Comment by tibetsprague** [comment]
same way people can follow users, daos and proposals and get all events associated with those entities

**Comment by jellegerbrandy** [comment]
(maybe github comments is not the best place to discuss the "why" of the features <3)

To be slightly more precise: the request is that the  `Event`  entity gets another field `scheme: ControllerScheme`, which is filled when it is appropriate (.e.g for the events that @tibetsprague mentioned: ProposalStageChange, VoteFlip, NewProposal, Stake, Vote).

**Comment by jellegerbrandy** [comment]
I'm closing this issue, as @A-Zak regards it as "not really needed"
