### ISSUE TITLE
Proposal_filter provides no way to filter by dao address

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#40]
alchemy needs a way to be able to find "all proposals within a DAO that are Open" or "all proposals within a DAO that expire before date X"

**Comment by jellegerbrandy** [comment]
Yes, this _does_ seem to work.

The `dao` field is not docuemnted inthe `Proposal_filter` list (in graphiql). The `Proposal` object has a `DAO` property, which is a structured entity of type DAO, not a string. So afaics there is no way i could have known that this worked: it is a documentaiton bug :-)

**Comment by orenyodfat** [comment]
> Yes, this _does_ seem to work.
> 
> The `dao` field is not docuemnted inthe `Proposal_filter` list (in graphiql). The `Proposal` object has a `DAO` property, which is a structured entity of type DAO, not a string. So afaics there is no way i could have known that this worked: it is a documentaiton bug :-)

<img width="1033" alt="screen shot 2018-12-23 at 16 39 09" src="https://user-images.githubusercontent.com/5994398/50384730-68effa80-06d1-11e9-8cbe-f4bf41e08b01.png">
