### ISSUE TITLE
changes in the subgraph for the Competition scheme

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#403]
I've tried to inventorize what we need on the basis of (the current version of) https://github.com/daostack/arc/blob/new_cr/contracts/schemes/Competition.sol and https://github.com/daostack/arc/blob/new_cr/contracts/schemes/ContributionRewardExt.sol, and the designs here https://app.zeplin.io/project/5c4de2851386a637a927c270/screen/5ddd58b133bfd010f35d6908

All these are subject to change, and i may have missed something...

# `Proposal`

the Proposal data Entity needs to be extended  a field:

```
competition: CompetitionProposal!
```

# CompetitionProposal

```
id: ID!
proposal: Proposal!
contract: Bytes!
avatar: DAO!
numberOfWinners
rewardSplit  //  <-- not sure how to best represent this...
startTime
votingStartTime
endTime
numberOfVotesPerVoters
contributionReward, //address of the contract to redeem from.
snapshotBlock
suggestions: [Suggestion!]
votes: [Vote!]
// PLUS THE FIELDS OF THE CONTRIBUTIONREWARDEXT
beneficiary: Bytes!
descriptionHash: String!
externalToken: Bytes!
votingMachine: Bytes!
reputationReward: BigInt!
nativeTokenReward: BigInt!
ethReward: BigInt!
externalTokenReward: BigInt!
executedAt: BigInt
nativeTokenRewardLeft;
reputationChangeLeft;
ethRewardLeft;
externalTokenRewardLeft;
```

# suggestion 

[Called "solution" in the UI]

```
id
proposal: Proposal!
descriptionHash: Bytes!
title: String! [from ipfs file at descriptionHash]
description: String! [from ipfs file at descriptionHash]
url: String! [[from ipfs file at descriptionHash]
suggester
votes: [Vote!]
totalVotes: BigInt
```

# vote 

```
proposal: Proposal!
suggestion: Suggestion!
voter: Address
reptutation: BigInt
```

# ??

- not sure what will be the best way to get the winners (after the comp ended) - but we can get these with the current model by geting the 
suggestions of a propsoal ordered by totalVotes, which should be good enough. alternatively, we can add a  `winners`
- not sure how to repsresent rewardSplit

**Comment by orenyodfat** [comment]
> not sure what will be the best way to get the winners (after the comp ended) - but we can get these with the current model by geting the
> suggestions of a propsoal ordered by totalVotes, which should be good enough. alternatively, we can add a winners

-Subgraph can maintain a sorted list of suggestions per proposal.

> not sure how to repsresent rewardSplit

we can have an entity which holds a list of the percentages rewards .(rewardSplit)
