### ISSUE TITLE
Escape quotes in the event.data field

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#406]
On mainnet right now we have this event which breaks Alchemy:

{
id: "0x05dad21e87898aa61aa766c8998703ad2da51612abc221df230ad8835550bbed", 
type: "NewProposal", 
data: "{ "title": ""untitled" Blockathon Art GIF" }", 
....
}

This breaks when I try to JSON.parse the data field to extract the title, because the quotes in the title are not escaped for JSON. Please add \ escaping to double quotes in the event.data field.

**Comment by orenyodfat** [comment]
this can and should be handle in alchemy side : both when pushing the proposals title and when when parsing it.

**Comment by orenyodfat** [comment]
@jellegerbrandy

**Comment by jellegerbrandy** [comment]
Ok, so the result of the subgraph query is this:

```
{
  "data": {
    "events": [
      {
        "data": "{ \"title\": \"\"untitled\" Blockathon Art GIF\" }",
        "id": "0x05dad21e87898aa61aa766c8998703ad2da51612abc221df230ad8835550bbed",
        "proposal": {
          "title": "\"untitled\" Blockathon Art GIF"
        }
      }
    ]
  }
}
```

* clear, the content of `data` is not valid json, so this is a bug that will break any client that expects to find json here.
* It seems to me that there is nothing wrong with the part where we "push the proposal title": the proposal title on the `Propsal` entity is correctly escaped here. I would not know what we could change in alchemy to improve this. (Also, proposals may be created outside of alchemy as well)
* There is, I think, no way to fix the problem on the alchemy side by trying to convert the `data` to valid JSON. (Suppose the data field looks like `{\"title\":\"h\",\"key\":\"value\"}` - it the title here `h` or `h","key":"vallue`?)
* So this has to be solved in this line: https://github.com/daostack/subgraph/blob/b1a5958a2ffd554c169cd52ea9c38faa79dd7ac0/src/domain/event.ts#L60 (and all similar lines), where you should escape the double quotes in the proposal title. 


















---------------------
(this is the query if if you nee it: ```{
  events(where: {
    
  id: "0x05dad21e87898aa61aa766c8998703ad2da51612abc221df230ad8835550bbed"}) {
    id
    data
    proposal {  
      title
    }
  }
}
```
```
