### ISSUE TITLE
Change type of `Event.type` to string

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#407]
Apparently, because `Event.type` is an enum, the subgraph does not implement the `_in` query parameter. 

I.e. we'd like to construct queries of the form:

`events (where: {type_in: ["VoteFlip", "Vote"])` 

This seems something that is forgotten by thegraph team to include in their generated grapql model. An easy workaround is to redefine the type of `Event.type` as a string.

**Comment by jellegerbrandy** [comment]
These are two different issues. I'll edit this one and create a new issue for adding the user to the VoteFlip and ProposalStateChange events.
