### ISSUE TITLE
Populate `user` field in VoteFlip and ProposalStateChange events

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#409]
Both these events are ultimate caused by a user, so in both cases, the value here should be the address of the `voter` causing the event

**Comment by ben-kaufman** [comment]
ProposalStateChange is not necessarily attributable to a voter though. I can put there the `event.transaction.from` if that works for you.

**Comment by jellegerbrandy** [comment]
true. Yes, that wil work as well.
