### ISSUE TITLE
implement "tokensNeededToPreBoost"

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#43]
as a property of the `proposal` entity. 
Alchemy shows "how much rep is needed to boost this proposal", and this  property should give us the threshold we need to reach to boost the proposal.

**Comment by jellegerbrandy** [comment]
this does not really address the original issue. But there are some doudbts now about the funciontality that alchemy earth actually needs, I'll re-open this issue if we still need it.

**Comment by tibetsprague** [comment]
ok so looks fine to calculate GENs left to boost , as long as we know the constant. does that constant come from the DAO? is it always the same?

**Comment by jellegerbrandy** [comment]
The "alphaconstant" that Oren mentinos is actually called "thresholdConst"  https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L34 (can you confirm, Oren?)

I'm not sure what the best practice is here - in my view it makes sense to index these parameters in the subgraph, but there is no real place. In any case, for now, we can get it from the contract itself directly.

**Comment by tibetsprague** [comment]
i think constants like this should be indexed on the DAO, since they can be customized per dao

**Comment by jellegerbrandy** [comment]
Ok, I'm reopening this AGAIN :-) because calculating it on the client and then keeping it in sync is a lot of work. So what we want is an attribute that perhaps is best called: `tokensNeededToPreBoost`, and given the formula: 
 `(S+/S-) > AlphaConstant^NumberOfBoostedProposal.`

we would get `tokensNeededToPreBoost = (alphaconst*NumberOfBoostedProposals * StakesAgainst) - StakesFor`

**Comment by orenyodfat** [comment]
I guess that alchemy would like to know : 
- upStake tokens needed to preBoost a Qued proposal.
- downStake tokens needed to Qued proposal from preBoosted.
How about the client will read the proposal entity from subgraph which will include current S+ and S- and proposal.confidenceThreshold (for the case of preBoosted)...and will do the calculation it self? 
The dao threshold can be calculated on the client side as well -alpha.power(NumberOfBoostedProposal) . so it need to know the number of current boosted proposal..and i guess it can have that,
@jellegerbrandy

**Comment by jellegerbrandy** [comment]
yes, @tibetsprague  has been working on implementing it on the client side, and in theory we can finish that work. However, I am not so happy with this type of solution because (1) the client really needs to do 2 queries to do this caluclation: get the numer of boosted proposals, and get the values from a single rpproposal. and it takes some bookkeeping to keep those in sync and updated, and it is a bit messy to do that client side;  and (2) the idea is that the alchemy "just shows" the data, the contracts and the subgraph handle the proposal logic, and the client glues all together - and in that view, the subgraph seems the right place to do these calclulations

**Comment by orenyodfat** [comment]
Due to assembly script limitation supporting floating points numbers in subgraph ..we decided to do these calculation on the client library side.
Subgraph will provide the upStake ,downStake and confidenceThreshold of a proposal .
The dao threshold will be added to the DAO entity ,which is already linked to the proposal entity.

**Comment by jellegerbrandy** [comment]
Ok, decided do do this client side. https://github.com/daostack/client/issues/103
