### ISSUE TITLE
members collection is still broken

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#45]
(this has taken away some hours of my life :-)

The members collection does not get populated with the DAO members that are created by the migration repo  

(Note that the members collection _does_ get populated with the members of the DAO that is created in `domain.spec.ts` )

Reproduce the issue:

```sh
docker-compose up graph-node
node ops/setup-env
```
Visit http://127.0.0.1:8000/subgraphs/name/daostack?query=%7B%0AreputationHolders%0A%7B%0Aid%2C%0A%20%20%2C%20balance%0A%2C%20address%2C%20contract%0A%7D%0A%7D%0A and see all reputation holders of the DAO that was deployed by setup-env.

Visit http://127.0.0.1:8000/subgraphs/name/daostack?query=%7B%0Amembers%20%7B%20id%2C%20reputation%20%7D%0A%20%20%0A%7D%0A and see an empty members collection.

Expected: members collection corresponds to tokenholders.

**Comment by dkent600** [comment]
Hopefully has been a learning experience  ;-)

**Comment by jellegerbrandy** [comment]
Yeah, i learned never just believe anyone who says "it is fixed" :-)

**Comment by orenyodfat** [comment]
@jellegerbrandy please verify #46
