### ISSUE TITLE
redeemer contract   rc.36 missing on v36_8 main net

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#450]
The client uses the latest redeemer contract version. This one is deployed and indexed on the ganache images as well as on https://thegraph.com/explorer/subgraph/daostack/v36_8_rinkeby, but not on main at https://thegraph.com/explorer/subgraph/daostack/v36_8

It is not difficult to work around, but given the inconsistency between test,staging and production, it seems that it is a mistake on your side:

Test with this query:
```
{ contractInfos (where:{  name:"Redeemer", version:"0.0.1-rc.36"}) {
  name
  version
}}
```

**Comment by ben-kaufman** [comment]
We don't have v36 on mainnet as for now. Closing this issue, if needed please open in the migration.

**Comment by jellegerbrandy** [comment]
your answer is factually false: there _is_ a v36 mainnet subgraph here: https://thegraph.com/explorer/subgraph/daostack/v36_8 and it does index a number of rc.36 contracts (like GenericScheme and Competitino)

**Comment by orenyodfat** [comment]
@ben-kaufman answer is correct .
these contracts (redeemer) from this version  are not deployed on mainnet .

**Comment by jellegerbrandy** [comment]
In the meantime, can you please advise what do do with alchemy that is test on local and staging using v36_8. Should I downgrade before going to production? Or should I wait?
