### ISSUE TITLE
accountsWithUnclaimedRewards_contains should not contain CR beneficiaries for proposals that are ExpiredInQueue

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#455]
Right now we are seeing available redemptions for ContributionReward beneficiaries on proposals that failed by Expiring in the queue, this should not be the case.

**Comment by ben-kaufman** [comment]
Hi, can you please provide a query which shows an example of the problem?

**Comment by tibetsprague** [comment]
{
  proposal(id: "0x35f7520462d2d6482b95da5e5febf262b0c80f704d7a6d0314209cf4dbb03616") {
    ...ProposalFields
    votes {
      id
      __typename
    }
    stakes {
      id
      __typename
    }
    __typename
  }
}

fragment ProposalFields on Proposal {
  id
  accountsWithUnclaimedRewards
  boostedAt
  closingAt
  confidenceThreshold
  competition {
    id
    endTime
    contract
    suggestionsEndTime
    createdAt
    numberOfVotesPerVoters
    numberOfWinners
    rewardSplit
    snapshotBlock
    startTime
    votingStartTime
    __typename
  }
  contributionReward {
    id
    beneficiary
    ethReward
    ethRewardLeft
    externalToken
    externalTokenReward
    externalTokenRewardLeft
    nativeTokenReward
    nativeTokenRewardLeft
    periods
    periodLength
    reputationReward
    reputationChangeLeft
    alreadyRedeemedReputationPeriods
    alreadyRedeemedExternalTokenPeriods
    alreadyRedeemedNativeTokenPeriods
    alreadyRedeemedEthPeriods
    __typename
  }
  createdAt
  dao {
    id
    schemes {
      id
      address
      __typename
    }
    __typename
  }
  description
  descriptionHash
  executedAt
  executionState
  expiresInQueueAt
  genericScheme {
    id
    contractToCall
    callData
    executed
    returnValue
    __typename
  }
  genesisProtocolParams {
    id
    activationTime
    boostedVotePeriodLimit
    daoBountyConst
    limitExponentValue
    minimumDaoBounty
    preBoostedVotePeriodLimit
    proposingRepReward
    queuedVotePeriodLimit
    queuedVoteRequiredPercentage
    quietEndingPeriod
    thresholdConst
    votersReputationLossRatio
    __typename
  }
  gpRewards {
    id
    __typename
  }
  scheme {
    ...SchemeFields
    __typename
  }
  gpQueue {
    id
    threshold
    votingMachine
    __typename
  }
  organizationId
  preBoostedAt
  proposer
  quietEndingPeriodBeganAt
  schemeRegistrar {
    id
    schemeToRegister
    schemeToRegisterParamsHash
    schemeToRegisterPermission
    schemeToRemove
    decision
    schemeRegistered
    schemeRemoved
    __typename
  }
  stage
  stakesFor
  stakesAgainst
  tags {
    id
    __typename
  }
  totalRepWhenCreated
  totalRepWhenExecuted
  title
  url
  votesAgainst
  votesFor
  votingMachine
  winningOutcome
  __typename
}

fragment SchemeFields on ControllerScheme {
  id
  address
  name
  dao {
    id
    __typename
  }
  canDelegateCall
  canRegisterSchemes
  canUpgradeController
  canManageGlobalConstraints
  paramsHash
  contributionRewardParams {
    id
    votingMachine
    voteParams {
      id
      queuedVoteRequiredPercentage
      queuedVotePeriodLimit
      boostedVotePeriodLimit
      preBoostedVotePeriodLimit
      thresholdConst
      limitExponentValue
      quietEndingPeriod
      proposingRepReward
      votersReputationLossRatio
      minimumDaoBounty
      daoBountyConst
      activationTime
      voteOnBehalf
      __typename
    }
    __typename
  }
  contributionRewardExtParams {
    id
    votingMachine
    voteParams {
      id
      queuedVoteRequiredPercentage
      queuedVotePeriodLimit
      boostedVotePeriodLimit
      preBoostedVotePeriodLimit
      thresholdConst
      limitExponentValue
      quietEndingPeriod
      proposingRepReward
      votersReputationLossRatio
      minimumDaoBounty
      daoBountyConst
      activationTime
      voteOnBehalf
      __typename
    }
    rewarder
    __typename
  }
  genericSchemeParams {
    votingMachine
    contractToCall
    voteParams {
      queuedVoteRequiredPercentage
      queuedVotePeriodLimit
      boostedVotePeriodLimit
      preBoostedVotePeriodLimit
      thresholdConst
      limitExponentValue
      quietEndingPeriod
      proposingRepReward
      votersReputationLossRatio
      minimumDaoBounty
      daoBountyConst
      activationTime
      voteOnBehalf
      __typename
    }
    __typename
  }
  schemeRegistrarParams {
    votingMachine
    voteRemoveParams {
      queuedVoteRequiredPercentage
      queuedVotePeriodLimit
      boostedVotePeriodLimit
      preBoostedVotePeriodLimit
      thresholdConst
      limitExponentValue
      quietEndingPeriod
      proposingRepReward
      votersReputationLossRatio
      minimumDaoBounty
      daoBountyConst
      activationTime
      voteOnBehalf
      __typename
    }
    voteRegisterParams {
      queuedVoteRequiredPercentage
      queuedVotePeriodLimit
      boostedVotePeriodLimit
      preBoostedVotePeriodLimit
      thresholdConst
      limitExponentValue
      quietEndingPeriod
      proposingRepReward
      votersReputationLossRatio
      minimumDaoBounty
      daoBountyConst
      activationTime
      voteOnBehalf
      __typename
    }
    __typename
  }
  numberOfQueuedProposals
  numberOfPreBoostedProposals
  numberOfBoostedProposals
  uGenericSchemeParams {
    votingMachine
    contractToCall
    voteParams {
      queuedVoteRequiredPercentage
      queuedVotePeriodLimit
      boostedVotePeriodLimit
      preBoostedVotePeriodLimit
      thresholdConst
      limitExponentValue
      quietEndingPeriod
      proposingRepReward
      votersReputationLossRatio
      minimumDaoBounty
      daoBountyConst
      activationTime
      voteOnBehalf
      __typename
    }
    __typename
  }
  version
  __typename
}

**Comment by tibetsprague** [comment]
It still needs to return GP rewards so stakers on expired proposals can get their GEN back
