### ISSUE TITLE
v37_2 seems to not include all contracts that should be indexed

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#463]
For example:

This `ContributionRewardExt` c ontract: https://rinkeby.etherscan.io/address/0x49e2516c807409ad539d0e50d9c8988c980cd22b#code

is used in this dAO: https://alchemy-competition-rinkeby.herokuapp.com/dao/0x2f931b0cf4fa92b912e6a4a354d8946f85b2dc18

But it is not among the contractInfos here:

https://thegraph.com/explorer/subgraph/daostack/v37_2_rinkeby

running this query:
```
{contractInfos (where:{address:"0x49e2516c807409ad539d0e50d9c8988c980cd22b"}) {
  id
}}
```

**Comment by ben-kaufman** [comment]
I don't know where you got this DAO address from, but it's incorrect. See addresses here: https://github.com/daostack/subgraph/pull/462/files#diff-9ddac6af411ae8810e1d588e0beb6d41
