### ISSUE TITLE
add "totalVotes" and "totalSubmissions"  to CompetitionProposal

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#468]
as in the title. At the moment, we are fetching all the votes just to count them.

**Comment by orenyodfat** [comment]
is it per proposal or per submission ? @theylon

**Comment by Theylon** [comment]
I'm not sure, this seems like it's strictly for subgraph optimization no?

**Comment by orenyodfat** [comment]
you want to count the number of vote per submission or per competitionProposal ?

**Comment by jellegerbrandy** [comment]
sorry, did not get back to this.

yes this is "stricly for subgraph optimization" -> meaning less and smaller queries. Perhaps a bit late now, but if you can fit it in?

We' dneed `totalVotes` (athe count of all votes for all submission) and `totalSubmissions` (the count of all submissions in the proposal)
