### ISSUE TITLE
"null value resolved for non-null field" errors in subgraph 38-0

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#469]
When trying to create a new test_env (in PR https://github.com/daostack/test_env/pull/28) I get the following errors running the following query.

You can reproduce by checking out the branch `subgraph_v38_0`, running `./release.sh -d` (will take a while) and then looking at `http://127.0.0.1:8000`.

The subgraph at https://thegraph.com/explorer/subgraph/daostack/v38_0_rinkeby does not seem to have this problem... so it may be bc of the proposals that I'm creating in the test_env environment (but this remained unchanged since the last release)

```
{
  "errors": [
    {
      "locations": [
        {
          "column": 15,
          "line": 5
        }
      ],
      "message": "Null value resolved for non-null field `genesisProtocolParams`"
    },
    {
      "locations": [
        {
          "line": 8,
          "column": 15
        }
      ],
      "message": "Null value resolved for non-null field `gpQueue`"
    }
  ]
}
```
```
          {
            proposals {
              id
              genesisProtocolParams {
                id
              }
              gpQueue {
                id
              }
            }  
          }
       
```

**Comment by jellegerbrandy** [comment]
I have more info now. This error occurs after creating a proposal in `ContributionRewardExt` version rc.39.

This contract is indexed in the subgrpah, so I'd expect it to not break the entire subgraph if I create a proposal in it.

**Comment by ben-kaufman** [comment]
Is this still an issue?
If yes please add instructions on how to reproduce, I couldn't reproduce this using the test-env, the client, or our deployed subgraphs.
