### ISSUE TITLE
 Make sure all schemes return schemeParams with voting machine params

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#493]
Right now i am trying to show the scheme params and voting machine params for an "UpgradeScheme" scheme and the subgraph is not giving me the scheme params at all. 

You can test this in ganache with Alchemy at http://127.0.0.1:3000/dao/0x69c348135b7540cfdcee5e19ca5a20c9d13a83e8/scheme/0x62c55c7587f92a2bc20cf22e08213a98da6407699c602fe3dc0f1996f60598e9

**Comment by ben-kaufman** [comment]
Hi @tibetsprague. We do not support the UpgradeScheme in the subgraph currently so we do not index anything from it.

**Comment by tibetsprague** [comment]
well @orenyodfat asked us to show scheme permissions in Alchemy for unknown schemes, so to do that we need to have access to the permissions in the subgraph

**Comment by orenyodfat** [comment]
we should be able to read schemePermission https://github.com/daostack/arc/blob/master/contracts/controller/Controller.sol#L507 for each registeredScheme . even if it unknown scheme .,
The issue title is confusing @tibetsprague . @ben-kaufman

**Comment by orenyodfat** [comment]
actually subgraph gives the permission of each register scheme even if it is unknown .
for example for dxDao (mainnet ) there are 4 unknown schemes.
you can query its permissions at https://thegraph.com/explorer/subgraph/daostack/v38_3  by :  
```
{
daos(id:"0x519b70055af55a007110b4ff99b0ea33071c720a"){
  name
  schemes{
    name
    canDelegateCall
    canRegisterSchemes
    canRegisterSchemes
    canManageGlobalConstraints
  }
}
}
```
