### ISSUE TITLE
add 3box profiles for dao members.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/subgraph#519]
see https://github.com/daostack/alchemy/issues/1583
and
https://github.com/graphprotocol/graph-node/releases/tag/v0.18.0

**Comment by orenyodfat** [comment]
for start lets index the standard fields :
name, image, coverPhoto, emoji, description

**Comment by tibetsprague** [comment]
just FYI the other things we need in Alchemy are the linked social accounts that come back from the 3box call Box.getVerifiedAccounts(profile), as well as the data we store in the DAOstack space for each user. I dont know if you can get that from the graph too or only the basic profile info

**Comment by ben-kaufman** [comment]
According to the Graph Node team, the 3box API is not yet stable enough for use in production, so we should wait with this integration. Closing this for now.
