### ISSUE TITLE
reputationholders are not correctly created

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#52]
To reproduce:

1. run the tests
1. visit http://127.0.0.1:8000/subgraphs/name/daostack?query=%7B%0A%20%20%20%20%20%20reputationContract%20(id%3A%20%220xee08445e0039971b65cff5f71851b34117d85cb4%22)%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20id%2C%20address%2C%20totalSupply%2C%20reputationHolders%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D

1. See that the totalsupply is 500, but reputationHolders is `null`
1. And also there are no reptuationHolders in the collection, etc.

This is the `TSST DAO` created in `domain.spec.ts`, and these are the founders of the DAO.

**Comment by jellegerbrandy** [comment]
I've created a failing test in the branch `6_reputationholders`

**Comment by orenyodfat** [comment]
reputationholders are low level entities. means that the subgraph should listen and map this events from a pre defined address (defined in the subgraph manifest file).

The domain.spec.ts test create a dao with forgeOrg which instance a new reputation contract which subgraph does not listen to this new created (by the test) contracts.

This will not be the case for the reputationHolders for the test dao created by the migration script ,(which the subgraph is listen to).

Any how I think you should get the dao members from the dao domain entity.

**Comment by ben-kaufman** [comment]
Is this issue still active?

**Comment by jellegerbrandy** [comment]
yes

**Comment by jellegerbrandy** [comment]
The problem is that the second test dao from the migration repo is broken, because it is not correctly or completely indexed. The quickest "solution" here is to remove that dao from the migration repo. We are not using it in tests for client or alchemy (I don' t know about subgraph)
