### ISSUE TITLE
index dao metadata

### ISSUE THREAD

**Issue by orenyodfat** [daostack/subgraph#545]
the event come from : 
https://github.com/daostack/arc/blob/arc-factory/contracts/controller/Avatar.sol#L169

**Comment by jellegerbrandy** [comment]
So, just to be sure, you will add a `metadata` property to the `DAO` entity of type `String`

The value of `metadata` will be the contents of the file that is found on IPFS under the hash given by `MetaDataEvent._metadata`  

we probably also want to add field called `metadataHash`, just like we do in the proposal entity (where we have `descriptoin` and `descriptionHash`)

**Comment by orenyodfat** [comment]
The content of metadata will be the content of the metadata field. 
{ metadata : “StringYouWantToIndex”} 

we will add also metadataHash .

**Comment by jellegerbrandy** [comment]
Isee you closed this. But when/how this will be released?
