### ISSUE TITLE
Incorrect event timestamp using ganache docker image

### ISSUE THREAD

**Issue by orenyodfat** [daostack/subgraph#548]
`{
   
  reputationHolders(where:{address:"0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1"}) {
    createdAt
    dao{
      id
      name
    }
  }
  
}`

run the above query on ganache image . 
some of the createdAt date are in the future .

This might be an issue with migration.

effect https://github.com/daostack/alchemy/issues/1684

**Comment by ben-kaufman** [comment]
This is because the migration increases the ganache time to boost a proposal in the test daos. I could make it increase the time in a few minutes instead of a few days like it does now though.

**Comment by orenyodfat** [comment]
https://github.com/daostack/migration/issues/325
