### ISSUE TITLE
Need a way to get the last token Approval event

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#55]
Alchemy needs to now how many tokens are currently approved. There is no way I can see to get that info fromt he subgraph. If te `TokenApproval` object is unique for a user/token pair, we can get that, but if more than 1 approval event happened, we need to get the last one, and there is no way to see which one that is.

Probably the most elegant solution would be if we add an allowances array to the TokenHolder entity that maps spenders to amounts. I.e. something like:

```
  {
        "balance": "1000000000000000000000",
        "contract": "0x79183957be84c0f4da451e534d5ba5ba3fb9c696",
        "id": "0x6abc6f657694652f91d04c35238727d9b414b640284835f69bc9e780c0efe11f",
        "allowances": {
             "0xAddressOfSpender" : 1234
        }
      }
```

**Comment by ben-kaufman** [comment]
This should track allowance to the address of the Genesis Protocol right?

**Comment by jellegerbrandy** [comment]
Well, I would keep it general, and just track all allowances, i.e. just save all the  `Allowance` event calls (I don't remember what the event is). In noraml usage in alchemy, the spender is the  genesisprotocol, but I see no reason to not also track the others...

**Comment by jellegerbrandy** [comment]
Reopening this. I think the "allowances" entity should also contain the token contract address that the allowance pertains to. This is important because of future-proofing (we will have to monitor different otkens in the future)

**Comment by jellegerbrandy** [comment]
Another thing that is issing is the possibility to query allowances by owner address and spender (i.e. the typical case), 
in the current implementation, the "owner" field on the allowances entity refers to a TokenHolder. This is (1) wrong (an account could have 0 token balance but will have an allowance) and (2) very inconvenient for querying (I see no way to get the allowance of an account for a certain spender in a single graphql query)

Solution: just use owner address, not a TokenHolder entity.

**Comment by jellegerbrandy** [comment]
closing this and making a new issue dedicated specific to fixing he allowance entity #101
