### ISSUE TITLE
subgraph crashed on trying to parse "descriptionHash"

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#555]
This is here https://thegraph.com/explorer/subgraph/daostack/v7_5_exp_rinkeby?selected=logs

```Subgraph instance failed to run: Failed to process trigger in block #6493128 (881bb503c22a0033f63e0b571f5f3a69da5d5b770351abf7fb52310def4f6ab9), transaction 5fb34b21c5ea4fa82e3f70ef117a8ff4c546e2a78e33cc8920458f3f2322347d: Failed to handle Ethereum event with handler "handleNewJoinAndQuitProposal": Mapping aborted at ~lib/@graphprotocol/graph-ts/index.ts, line 1098, column 4, with message: JSON value is not a string., code: SubgraphSyncingFailure, id: QmYr5KTLrUPaqnJNjb26982nHHVzNnVwUXnB5UZNXFKnHa```

**Comment by orenyodfat** [comment]
this is the ipfs file ?!
https://ipfs.globalupload.io/QmYr5KTLrUPaqnJNjb26982nHHVzNnVwUXnB5UZNXFKnHa 
something is wrong..

**Comment by orenyodfat** [comment]
this is the file..which is not formatted as it should be : 

{"description":{"dao":"0x0495415bfd7525e315dd5ae7d46150ce90f87fad","title":"A test proposal on Fri May 15 2020 16:19:09 GMT+0200 (CEST)","description":"Some description","files":[],"images":[],"links":[],"funding":"0186a0"}} 

subgraph should not crash though...it will be fixed.
