### ISSUE TITLE
Subscriptions are not stable and break

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#58]
Reproduce like this:

- `docker-compose up` 

in another shell
- `npm run jest -- test/integration/Subscription.spec.ts`

This test passes, so we know the subscription works.

Now try running the test several times in quick succession:

`for run in {1..10}; do npm run jest -- test/integration/Subscription.spec.ts ; done`

The test failes after 2 or 3 runs.

For reproducing, consider using this branch https://github.com/daostack/subgraph/pull/57 which does not use  setTimeout to wait for the result.

This issue is the twin brother of https://github.com/daostack/client/issues/36

**Comment by orenyodfat** [comment]
this subscribe in a loop works  :
https://github.com/daostack/subgraph/blob/gh-issue-52/test/integration/Subscription.spec.ts#L44

**Comment by orenyodfat** [comment]
this might be the fix https://github.com/graphprotocol/graph-node/pull/648 .
