### ISSUE TITLE
proposal votesFor count should be correct

### ISSUE THREAD

**Issue by dkent600** [daostack/subgraph#581]
This is in the ganache docker subgraph.  I haven't tried another subgraph.

I run this query against a ContributionReward proposal:

```
{
  proposals(
    where: {id: "0xdd451a3e21353016c2022998dc4cedc16488c4627597f1b9cad2e7fcdc01acd5"}) 
  {
    id
    votes { id }
    votesAgainst
    votesFor
  }
}
```

And I see this:

![image](https://user-images.githubusercontent.com/1821666/88275737-e021b200-ccab-11ea-8108-f59418d604dc.png)

Note the `votesFor` value is nonsense.  Should be "4".

**Comment by ben-kaufman** [comment]
@dkent600 can you please add this in the query (within the proposals query) and post the result?
```
votes {
      reputation
    }
    dao {
      reputationHolders {
        balance
      }
    }
```

**Comment by dkent600** [comment]
> @dkent600 can you please add this in the query (within the proposals query) and post the result?

![image](https://user-images.githubusercontent.com/1821666/88281100-14e63700-ccb5-11ea-8f28-34ad697c691d.png)

**Comment by ben-kaufman** [comment]
So looks like the subgraph is ok... I guess the reputation flow changed a bit when you used the ganache, but everything looks correcty from the subgraph side.

**Comment by dkent600** [comment]
> So looks like the subgraph is ok... I guess the reputation flow changed a bit when you used the ganache, but everything looks correcty from the subgraph side.

Oh, I think what you're saying is that votesFor should not be "4" (the count of votes) as I suggested in the description, but rather the amount of rep vote for, and thus the value is correct.  Sorry for the distraction.
