### ISSUE TITLE
Rewards entity is not populated

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#59]
I created a proposal with an ethReward and reputationReward. These props do get populated, but the `rewards` collection remains empty.

It may be that I misunderstood the point of the  `rewards` entity. 

This is the output of the query:
```
{
  "data": {
    "proposal": {
      "beneficiary": "0xffcf8fdee72ac11b5c542428b35eef5769c409f0",
      "ethReward": "10",
      "id": "0xc31f2952787d52a41a2b2afd8844c6e295f1bed932a3a433542d4c420965028e",
      "reputationReward": "10",
      "rewards": [],
      "tokensReward": "10"
    }
  }
}
```

**Comment by jellegerbrandy** [comment]
So what I'd _expect_ is that the rewards collectiong ets populated with _all_ the rewards associated with the proposal. This includes the `reputationReward', `tokensReward`, `externaltokensReward` and  and `ethReward` but also
- reputation reward for proposer
- reputation reward for voter
- token reward for voter
- staker rewards

Alchemy also tells the user things like "if you vote for this, you get X".

**Comment by ben-kaufman** [comment]
It seems that right now the `Reward` entity is not implemented at all, I'll work on implementing that.

**Comment by orenyodfat** [comment]
what I thought about is upon the execution event to iterate on all voters,stakers and proposer , call the redeem function for each and fill up the Reward table.
It might be not optimal re timing ...
@ben-kaufman
