### ISSUE TITLE
feature request: add token balances to the DAO object

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#62]
It would be _very_ convenient if the DAO Entity would track the various balances:

- nativeTokenBalance
- ethBalance
- reputationBalance

**Comment by jellegerbrandy** [comment]
yes, i mean the balances fo the DAO itself. I did not think it trough, but in theory the DAO could have a reputationBalance. In practice, though, that will (probably) always be 0, and so we wil lnot show it in alchemy, and so we do not need to implement it.

About the ether balance: it is a choice we need to make. I'd argue for also indexing the ETH balances in the subgraph instead of using the `getBalance()` function that we implemented in the client lib (perhaps using an `ethHolder` entity), because (1) it makes the front-end code much simpler and (2) because the `getBalance()` functino si relatively expensive, because we need to check the balance on each block, which are a lot of requests if we show the member list. What do you think?

**Comment by ben-kaufman** [comment]
I'm not really sure how you would implement an `ethholder` entity...
It's very tricky and inefficient to constantly track and index the eth balances.

**Comment by jellegerbrandy** [comment]
Yes, it is tricky and ineffcient, and so we do not want to do it client side in alchemy but server side in the subgraph. I.e. instead of having 10.000 clients constantly polling for the balances, we will have one subgraph doing it.

**Comment by ben-kaufman** [comment]
But if the subgraph does that it will need to store and trach a lot of unnecessary data instead of each client monitoring the data they need.

**Comment by orenyodfat** [comment]
This feature need to be specified and well defined.
graph-node does not support that yet.
I guess that we need to come out with a workaround out of the scope of graph-node.
@jellegerbrandy

**Comment by orenyodfat** [comment]
pr #114 add the dao as a member of the dao so it will have all property of a dao member
the dao member count exclude the dao member

**Comment by jellegerbrandy** [comment]
we laready have an "ethBalance" watcher in the client library, we can use that (it is just sort of expensive, but it shoudl work)

**Comment by ben-kaufman** [comment]
Can I close this issue or is there something missing to finish it?

**Comment by jellegerbrandy** [comment]
yeah the eth balance is missing but it does not depend on us. Closing this for peace of mind :-)
