### ISSUE TITLE
"proposal.proposer" should just be an address (not a "member" instance)

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#75]
this is because the proposer could not be a member of the DAO

**Comment by ben-kaufman** [comment]
I think that was already addressed in a previous PR.
https://github.com/daostack/subgraph/blob/master/src/domain/schema.graphql#L48

**Comment by jellegerbrandy** [comment]
:+1:  I should first do upgrade before making new issues :-)
https://github.com/daostack/client/issues/55
