### ISSUE TITLE
tests should be independent

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#89]
Some tests depend on other tests to run first. This makes development cycles very long because you ned to run all the the tests togethe, and this problem will get worse as the test suite grows.

So, all tests should be independent.

**Comment by jellegerbrandy** [comment]
single tests can be run using `npm run test -- test/integration/Reputation.spec.ts`

**Comment by orenyodfat** [comment]
which test is not independent ?

**Comment by jellegerbrandy** [comment]
ask @ben-kaufman who told me it was so :-)

**Comment by ben-kaufman** [comment]
@orenyodfat We just had that problem yesterday with the DAOToken failing when the order of the tests changed. I'm not sure exactly which tests but I know a few, we would need to read through the tests and run them separately to identify the places dependent on others.
