### ISSUE TITLE
proposal.confidence is broken

### ISSUE THREAD

**Issue by orenyodfat** [daostack/subgraph#90]
test a case where the proposal is boosted...or preboosted where the confidence level should be > 0

**Comment by ben-kaufman** [comment]
It should be 0, as confidence is an int rounded down.

**Comment by jellegerbrandy** [comment]
Confidence = stakesFor/StakesAgainst.

If we represent that fraction by an integer, it will have way to little precision to be useful. (It will be 0 if stakesFor < stakesAgainst, etc). Need to store it with more precision, either as a flot, or as "stakesFor/StakesAgainst * 100" (i.e. as a "percentage") or perhaps with even more precision (depends a bit on what we are expecting)

**Comment by ben-kaufman** [comment]
That's also an option. But I would like to keep it consistent with the `_score` function from GP, so if we change that let's make sure it's consistent (@orenyodfat can we make this function public)?

**Comment by orenyodfat** [comment]
@ben-kaufman score is already public

**Comment by ben-kaufman** [comment]
Oh ok, I was looking in the wrong contract...

**Comment by orenyodfat** [comment]
@jellegerbrandy no need to store it as float as in the contract it is uint256/uint256 ...which is anyhow rounded down.

**Comment by jellegerbrandy** [comment]
This is blocking now, +++1

**Comment by jellegerbrandy** [comment]
just for refeence: this is the `_score` functin in the contract: https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L723
