### ISSUE TITLE
implement expiresInQueueAt

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#93]
We need an `expiresAt` value as a property on the Proposal entity

in  Alchemy, proposals are moved to the "history" tab once they expire. This cannot be done on the basis of the on-chain proposal state, because that will only be updated once `execute()` is called. Instead, Alchemy categorizes the proposals on the basis of a calculated "expected") expirty date.

see https://github.com/daostack/alchemy/issues/276 for the corresponding alchemy issue

i remember that in a previous iteratino, such a field existed, so it perhaps worth the trouble to dig that up.

**Comment by ben-kaufman** [comment]
@jellegerbrandy Please just add that in the right position in the task board.

**Comment by ben-kaufman** [comment]
I don't exactly remember how that should be calculated, can you please write that here?

**Comment by jellegerbrandy** [comment]
I am not completely sure either but I assupose what we are interested in two cases:

* state of the proposal changes to "expiresInQueue"  (for unboosted proposals),
which is decided on this line: https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L512: so if the proposal is queued, expiresAt should be set at `proposal.times[0] + params.queuedVotePeriodLimit`

* and for boosted proposals, the relevant line is https://github.com/daostack/infra/blob/master/contracts/votingMachines/GenesisProtocolLogic.sol#L561, and the value should be `proposal.times[1] + proposal.currentBoostedVotePeriodLimit`

I think these are the only two cases. :

**Comment by jellegerbrandy** [comment]
We need the first item (i.e. when the proposal will expire in queue) for 
https://github.com/daostack/client/issues/102

We can all it `expiresInQueueAt` (?)

**Comment by orenyodfat** [comment]
- a proposal entity already has this info  . the sum can done in the client side.
   - proposal.times[0]+params.queuedVotePeriodLimit == proposal.createdAt + proposal.queuedVotePeriodLimit

- please note that a proposal can pass the expiresInQueueAt and still be alive as it on Boosted or PreBoosted stage.

**Comment by jellegerbrandy** [comment]
* yes,  we can calculate the value easily, but we need to **query** on that field, and so we need it as a primitve property on the enitty. As per the spec here: https://docs.google.com/document/d/1cYSX9Z6RmjSlJLPVKm6fwi4nnk2xrB0-NqXngVv61TY/edit#heading=h.mfc7h4cnlwkq we want to show all proposals that are (1) have state = qeued and (2) are not expired yet.  

* yes I think we have covered these cases in the google doc

**Comment by orenyodfat** [comment]
does query on a sum of filed will not work ?

**Comment by jellegerbrandy** [comment]
no, that is not how graphql works
