### ISSUE TITLE
Member entity should be populated with token holders as well

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#97]
So the way the client is set up and the members collection is currently used, it would be very conveneint to have a member collection contain:

* all reptuation holders (as it is now)
* all token holders (i.e. not only those who have reputation, but also those token holders that have 0 rep)

**Comment by ben-kaufman** [comment]
You mean the holder of the DAOToken (not GEN) right?

**Comment by orenyodfat** [comment]
Not sure about thus request as Token holders is a wider set than dao members.
@jellegerbrandy

**Comment by jellegerbrandy** [comment]
Yes, that was sort of the point of this issue: to make hte member collection larger than just reputation holders.

My reasoning was this:

- we show account information (balances of REP, GEN, local DAO tokens) in various places in the app: the member list, the logged-in user profile, popoups for the proposers and receivers, maybe later also voters.
- the current `member` entity is only useful for the members page - the logge din user, proposers etc do not necessarily have REP, so they would not be in the member collection.
- it would be useful to have a single place in the subgraph where we can find that information, i.e. an "accounts" collection with these three balances. The member collection seems the most convenient place.

On the other hand, I am checking the designs on zeplin now, and cannot find any specs what token balances to show. @A-Zak , can you enligthen us here?
-

**Comment by jellegerbrandy** [comment]
btw: Adding all tokenholders to the members collection is also consistent with the exception we now made for the dao (that is a member but not a reputaiton holder)

**Comment by ben-kaufman** [comment]
I don't think you can count all GEN holders as members in a particular DAO though, so the only thing we can track like that is the holders of the DAO token.

**Comment by ben-kaufman** [comment]
@jellegerbrandy is this still an issue?
